package nta.med.ext.phr.glossary;

/**
 * @author DEV-TiepNM
 */
public enum Message {

	MESSAGE_VERIFY_KCCK_SUCCESS("success.kcck"),
	MESSAGE_VERIFY_KCCK_FAIL("fail.kcck"),
    MESSAGE_SUCCESS("message.success"),
    MESSAGE_FAIL("message.fail"),
    MESSAGE_DUPLICATE_EMAIL("fail.email.duplicate"),
	MESSAGE_ACCOUNT_ALREADY_ACTIVE("fail.email.aready.active"),
    MESSAGE_INVALID_INPUT_PARAM("fail.invalid.input.param"),
    MESSAGE_LOGIN_IS_NOT_VERIFY_YET("fail.login.is.not.verify.yet"),
    MESSAGE_LOGIN_IS_FIRST("fail.first.change.password.required"),
    MESSAGE_LOGIN_IS_FAIL("fail.login"),
    MESSAGE_CHANGE_PASSWORD_FAIL("change.password.fail"),
    MESSAGE_CHANGE_PASSWORD_TOKEN_NULL("fail.change.password.token.null"),
    MESSAGE_CHANGE_PASSWORD_TOKEN_INVALID("fail.change.password.token.invalid"),
	MESSAGE_TOKEN_INVALID("fail.token.invalid"),
    MESSAGE_PROFILE_NOT_FOUND("fail.profile.not_found"),
    MESSAGE_HOSP_NOT_FOUND("fail.hospitalcode.not_found"),
    MESSAGE_PATIENT_NOT_FOUND("fail.patientcode.not_found"),
    MESSAGE_PROFILE_HOSP_PATIENT("fail.duplicate.all.profile.patient.hosp"),
	MESSAGE_LOGOUT_SUCCESS("success.logout"),
	MESSAGE_RESET_PASSWORD_SUCCESS("success.reset.password"),
	MESSAGE_VERIFY_SUCCESS("success.verify"),
	MESSAGE_VERIFY_PATIENT_KCCK_FAIL("verify.account.kcck.fail"),
	MESSAGE_RESET_PASSWORD_EMAIL_UNREGISTERED("reset.password.email.unregistered"),
    MESSAGE_ENTITY_NOT_FOUND_FAIL("fail.entity.not_found"),
    STANDARD_FOOD_NOT_FOUND_FAIL("fail.stand_found_menu.not_found"),
    MESSAGE_REQUEST_INPUT_FAIL("fail.input"),
    MESSAGE_MEDICINE_LIST_EMPTY("medicine.list.empty"),
    FACEBOOK_REGISTER_ID_REQUIRED("facebook.id.required"),
    FACEBOOK_EMAIL_REQUIRED("email.required"),
    FACEBOOK_BIRTH_REQUIRED("birth.required"),
    FACEBOOK_ACCESS_TOKEN_INVALID("facebook.access.token.invalid"),
    FACEBOOK_ID_INVALID("facebook.id.invalid"),
    FACEBOOK_ID_IN_USED("facebook.id.in.used"),
	FACEBOOK_LOGIN_FAIL("fail.login.facebook"),
	FACEBOOK_REGISTER_FAIL("fail.register.facebook"),
    GENDER_REQUIRED("gender.required"),
	BIRTHDAY_REQUIRED("birthday.required"),
	INPUT_REQUIRED("input.required"),
	HEALTH_PERC_FAT_REQUIRED("perc_fat.required"),
	HEALTH_WEIGHT_REQUIRED("weight.required"),
	HEALTH_HEIGHT_REQUIRED("height.required"),
	HEALTH_BMI_REQUIRED("bmi.required"),
	HEALTH_NOT_FOUND("health.id.not.found"),
	HEALTH_TYPE_NOT_EXIST("health.type.not.exist"),
	HEALTH_LIST_IS_EMPTY("health.list.empty"),
	DATETIME_RECORD_REQUIRED("datetime_record.required"),
	ACCOUNT_ID_INVALID("account.id.invalid"),
	ACCOUNT_WITH_TYPE_AGREEMENT_UPDATED("account.with.type.agreement.updated"),
	TEMP_TEMPERATURE_REQUIRED("temperature.required"),
	TEMP_HEARTRATE_REQUIRED("pulse.required"),
	TEMP_BREATH_REQUIRED("breath.required"),
	TEMP_BP_REQUIRED("low.and.high.blood.pressure.required"),
	TEMP_TEMPERATURE_DELETED("temp.temperature.deleted"),
	TEMP_HEARTRATE_DELETED("temp.heartrate.deleted"),
	TEMP_BREATH_DELETED("temp.breath.deleted"),
	TEMP_BP_DELETED("temp.bp.deleted"),
	TEMP_NOT_FOUND("temp.id.not.found"),
	TEMP_TYPE_NOT_EXIST("temp.type.not.exist"),
	TEMP_LIST_IS_EMPTY("temp.list.empty"),
	FITNESS_ID_NOT_FOUND("fitness.id.not.found"),
	FITNESS_TYPE_NOT_EXIST("fitness.type.not.exist"),
	FITNESS_STEPS_REQUIRED("fitness.steps.count.required"),
	FITNESS_DISTANCE_REQUIRED("fitness.walk.run.distance.required"),
	FITNESS_STEPS_DELETED("fitness.steps.deleted"),
	FITNESS_DISTANCE_DELETED("fitness.distance.deleted"),
	FITNESS_LIST_IS_EMPTY("fitness.list.empty"),
	FOOD_EATING_TIME_REQUIRED("eating.time.required"),
	FOOD_KCAL_REQUIRED("kcal.required"),
	FOOD_CARBOHYDRATE_REQUIRED("carbohydrate.required"),
	FOOD_TOTAL_FAT_REQUIRED("total.fat.required"),
	FOOD_CALORY_DELETED("food.calory.deleted"),
	FOOD_CARBOHYDRATE_DELETED("food.carbohydrate.deleted"),
	FOOD_TOTAL_FAT_DELETED("food.total.fat.deleted"),
	FOOD_NOT_FOUND("food.id.not.found"),
	FOOD_TYPE_NOT_EXIST("food.type.not.exist"),
	FOOD_LIST_IS_EMPTY("food.list.empty"),
	GROWTH_ID_NOT_FOUND("growth.id.not.found"),
	GROWTH_TYPE_NOT_EXIST("growth.type.not.exist"),
	GROWTH_HEIGHT_REQUIRED("growth.height.required"),
	GROWTH_WEIGHT_REQUIRED("growth.weight.run.distance.required"),
	GROWTH_HEIGHT_DELETED("growth.height.deleted"),
	GROWTH_WEIGHT_DELETED("growth.weight.deleted"),
	GROWTH_LIST_IS_EMPTY("growth.list.empty"),
	BABY_PROFILE_FULL_NAME_REQUIRED("baby.profile.full.name.required"),
	BABY_PROFILE_FULL_NAME_KANA_REQUIRED("baby.profile.full.name.kana.required"),
	BABY_PROFILE_BIRTHDAY_REQUIRED("baby.profile.birthday.required"),
	BABY_PROFILE_RELATIONSHIP_REQUIRED("baby.profile.relationship.required"),
	BABY_PROFILE_GENDER_REQUIRED("baby.profile.gender.required"),
	BABY_PROFILE_GROWTH_HEIGHT_MODEL_REQUIRED("baby.profile.growth.height.model.required"),
	BABY_PROFILE_GROWTH_HEIGHT_REQUIRED("baby.profile.growth.height.required"),
	BABY_PROFILE_GROWTH_HEIGHT_ID_REQUIRED("baby.profile.growth.height.id.required"),
	BABY_PROFILE_GROWTH_WEIGHT_MODEL_REQUIRED("baby.profile.growth.weight.model.required"),
	BABY_PROFILE_GROWTH_WEIGHT_REQUIRED("baby.profile.growth.weight.required"),
	BABY_PROFILE_GROWTH_WEIGHT_ID_REQUIRED("baby.profile.growth.weight.id.required"),
	LIFE_STYLE_TIME_START_SLEEP_REQUIRED("time.start.sleep.required"),
	LIFE_STYLE_TIME_WAKE_UP_REQUIRED("time.wake.up.required"),
	LIFE_STYLE_TOTAL_HOUR_SLEEP_REQUIRED("total.hour.sleep.required"),
	LIFE_STYLE_LIST_EMPTY("list.life.style.empty"),
	DRUG_PRESCRIPTION_ID_NOT_FOUND("prescription.id.not.found"),
	DRUG_MEDICINE_ID_NOT_FOUND("medicine.id.not.found"),
	UDID_INVALID("profile.udid.invalid.for.sync"),
	SUCCESS("SUCCESS"),
    FAIL("FAIL");
	

	
    private String value;

    Message(String value) {
        this.value =value;
    }
    public String getValue()
    {
        return value;
    }

}
