//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"END1001U02GrdPurposeResponse")]
  public partial class END1001U02GrdPurposeResponse : global::ProtoBuf.IExtensible
  {
    public END1001U02GrdPurposeResponse() {}
    
    private readonly global::System.Collections.Generic.List<END1001U02GrdPurposeInfo> _grd_purpose_item = new global::System.Collections.Generic.List<END1001U02GrdPurposeInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grd_purpose_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<END1001U02GrdPurposeInfo> grd_purpose_item
    {
      get { return _grd_purpose_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
