//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ORCALibGetClaimDiagnosisResponse")]
  public partial class ORCALibGetClaimDiagnosisResponse : global::ProtoBuf.IExtensible
  {
    public ORCALibGetClaimDiagnosisResponse() {}
    
    private readonly global::System.Collections.Generic.List<ORCALibGetClaimDiagnosisInfo> _claim_diagnosis_item = new global::System.Collections.Generic.List<ORCALibGetClaimDiagnosisInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"claim_diagnosis_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ORCALibGetClaimDiagnosisInfo> claim_diagnosis_item
    {
      get { return _claim_diagnosis_item; }
    }
  
    private bool _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
