//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: shunou_service.proto
// Note: requires additional types generated from: rpc.proto
// Note: requires additional types generated from: shunou_model.proto

namespace IHIS.CloudConnector.Messaging
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShunouResponse")]
  public partial class ShunouResponse : global::ProtoBuf.IExtensible
  {
    public ShunouResponse() {}
    
    private PatientInformation _patient_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"patient_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PatientInformation patient_info
    {
      get { return _patient_info; }
      set { _patient_info = value; }
    }
    private readonly global::System.Collections.Generic.List<IncomeInformation> _income_information = new global::System.Collections.Generic.List<IncomeInformation>();
    [global::ProtoBuf.ProtoMember(2, Name=@"income_information", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IncomeInformation> income_information
    {
      get { return _income_information; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}