//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHIS.CLIS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IHIS.CLIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        internal static string CAP_001 {
            get {
                return ResourceManager.GetString("CAP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        internal static string CAP_002 {
            get {
                return ResourceManager.GetString("CAP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string CAP_003 {
            get {
                return ResourceManager.GetString("CAP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string CAP_004 {
            get {
                return ResourceManager.GetString("CAP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服薬情報コード.
        /// </summary>
        internal static string COL_DRUG_CODE_TEXT {
            get {
                return ResourceManager.GetString("COL_DRUG_CODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検査項目コード.
        /// </summary>
        internal static string COL_ORDER_CODE_TEXT {
            get {
                return ResourceManager.GetString("COL_ORDER_CODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年齢を正しく入力してください。.
        /// </summary>
        internal static string MSG_001 {
            get {
                return ResourceManager.GetString("MSG_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間を正しく入力してください。.
        /// </summary>
        internal static string MSG_002 {
            get {
                return ResourceManager.GetString("MSG_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加するために、選択してください。.
        /// </summary>
        internal static string MSG_003 {
            get {
                return ResourceManager.GetString("MSG_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリニックの治験を選択してください。.
        /// </summary>
        internal static string MSG_004 {
            get {
                return ResourceManager.GetString("MSG_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}:{1}」患者さんは別の治験にも参加しています。.
        /// </summary>
        internal static string MSG_005 {
            get {
                return ResourceManager.GetString("MSG_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」治験を削除してもよろしいでしょうか？.
        /// </summary>
        internal static string MSG_006 {
            get {
                return ResourceManager.GetString("MSG_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この患者さんは存在しません。.
        /// </summary>
        internal static string MSG_007 {
            get {
                return ResourceManager.GetString("MSG_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この患者さんは治験に追加されました。.
        /// </summary>
        internal static string MSG_008 {
            get {
                return ResourceManager.GetString("MSG_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}:{1}」患者さんは別の治験にも参加しています。.
        /// </summary>
        internal static string MSG_009 {
            get {
                return ResourceManager.GetString("MSG_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更されたデータがありますので、.
        /// </summary>
        internal static string MSG_012 {
            get {
                return ResourceManager.GetString("MSG_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存が完了しました。.
        /// </summary>
        internal static string MSG_013 {
            get {
                return ResourceManager.GetString("MSG_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存が失敗しました。.
        /// </summary>
        internal static string MSG_014 {
            get {
                return ResourceManager.GetString("MSG_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参加患者番号を入力してください。.
        /// </summary>
        internal static string MSG_015 {
            get {
                return ResourceManager.GetString("MSG_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 傷病コード.
        /// </summary>
        internal static string SANG_CODE_TEXT {
            get {
                return ResourceManager.GetString("SANG_CODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 傷病開始日.
        /// </summary>
        internal static string SANG_START_DATE_TEXT {
            get {
                return ResourceManager.GetString("SANG_START_DATE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        internal static string SEX_FEMALE {
            get {
                return ResourceManager.GetString("SEX_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        internal static string SEX_MALE {
            get {
                return ResourceManager.GetString("SEX_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存してもよろしいでしょうか？.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
    }
}
