////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.5420
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace IHIS.CLIS {
//    using System;
    
    
//    /// <summary>
//    ///   A strongly-typed resource class, for looking up localized strings, etc.
//    /// </summary>
//    // This class was auto-generated by the StronglyTypedResourceBuilder
//    // class via a tool like ResGen or Visual Studio.
//    // To add or remove a member, edit your .ResX file then rerun ResGen
//    // with the /str option, or rebuild your VS project.
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    internal class CLIS2015U03 {
        
//        private static global::System.Resources.ResourceManager resourceMan;
        
//        private static global::System.Globalization.CultureInfo resourceCulture;
        
//        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
//        internal CLIS2015U03() {
//        }
        
//        /// <summary>
//        ///   Returns the cached ResourceManager instance used by this class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Resources.ResourceManager ResourceManager {
//            get {
//                if (object.ReferenceEquals(resourceMan, null)) {
//                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IHIS.CLIS.CLIS2015U03", typeof(CLIS2015U03).Assembly);
//                    resourceMan = temp;
//                }
//                return resourceMan;
//            }
//        }
        
//        /// <summary>
//        ///   Overrides the current thread's CurrentUICulture property for all
//        ///   resource lookups using this strongly typed resource class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Globalization.CultureInfo Culture {
//            get {
//                return resourceCulture;
//            }
//            set {
//                resourceCulture = value;
//            }
//        }
        
//        internal static System.Drawing.Point addPatientButton_Location {
//            get {
//                object obj = ResourceManager.GetObject("addPatientButton.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size addPatientButton_Size {
//            get {
//                object obj = ResourceManager.GetObject("addPatientButton.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int addPatientButton_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("addPatientButton.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to ⇒.
//        /// </summary>
//        internal static string addPatientButton_Text {
//            get {
//                return ResourceManager.GetString("addPatientButton.Text", resourceCulture);
//            }
//        }
        
//        internal static bool ageCheckBox_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("ageCheckBox.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point ageCheckBox_Location {
//            get {
//                object obj = ResourceManager.GetObject("ageCheckBox.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size ageCheckBox_Size {
//            get {
//                object obj = ResourceManager.GetObject("ageCheckBox.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int ageCheckBox_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("ageCheckBox.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 年齢.
//        /// </summary>
//        internal static string ageCheckBox_Text {
//            get {
//                return ResourceManager.GetString("ageCheckBox.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point ageFromTextBox_Location {
//            get {
//                object obj = ResourceManager.GetObject("ageFromTextBox.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static int ageFromTextBox_MaxLength {
//            get {
//                object obj = ResourceManager.GetObject("ageFromTextBox.MaxLength", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size ageFromTextBox_Size {
//            get {
//                object obj = ResourceManager.GetObject("ageFromTextBox.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int ageFromTextBox_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("ageFromTextBox.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.HorizontalAlignment ageFromTextBox_TextAlign {
//            get {
//                object obj = ResourceManager.GetObject("ageFromTextBox.TextAlign", resourceCulture);
//                return ((System.Windows.Forms.HorizontalAlignment)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point agePanel_Location {
//            get {
//                object obj = ResourceManager.GetObject("agePanel.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size agePanel_Size {
//            get {
//                object obj = ResourceManager.GetObject("agePanel.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int agePanel_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("agePanel.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point ageToTextBox_Location {
//            get {
//                object obj = ResourceManager.GetObject("ageToTextBox.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static int ageToTextBox_MaxLength {
//            get {
//                object obj = ResourceManager.GetObject("ageToTextBox.MaxLength", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size ageToTextBox_Size {
//            get {
//                object obj = ResourceManager.GetObject("ageToTextBox.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int ageToTextBox_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("ageToTextBox.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.HorizontalAlignment ageToTextBox_TextAlign {
//            get {
//                object obj = ResourceManager.GetObject("ageToTextBox.TextAlign", resourceCulture);
//                return ((System.Windows.Forms.HorizontalAlignment)(obj));
//            }
//        }
        
//        internal static System.Drawing.Font btnList_Font {
//            get {
//                object obj = ResourceManager.GetObject("btnList.Font", resourceCulture);
//                return ((System.Drawing.Font)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point btnList_Location {
//            get {
//                object obj = ResourceManager.GetObject("btnList.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size btnList_Size {
//            get {
//                object obj = ResourceManager.GetObject("btnList.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int btnList_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("btnList.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static bool clisJoiningCheckBox_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("clisJoiningCheckBox.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point clisJoiningCheckBox_Location {
//            get {
//                object obj = ResourceManager.GetObject("clisJoiningCheckBox.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size clisJoiningCheckBox_Size {
//            get {
//                object obj = ResourceManager.GetObject("clisJoiningCheckBox.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int clisJoiningCheckBox_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("clisJoiningCheckBox.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 参加中治験.
//        /// </summary>
//        internal static string clisJoiningCheckBox_Text {
//            get {
//                return ResourceManager.GetString("clisJoiningCheckBox.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point clisJoinPanel_Location {
//            get {
//                object obj = ResourceManager.GetObject("clisJoinPanel.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size clisJoinPanel_Size {
//            get {
//                object obj = ResourceManager.GetObject("clisJoinPanel.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int clisJoinPanel_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("clisJoinPanel.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static bool dateComeCheckBox_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("dateComeCheckBox.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point dateComeCheckBox_Location {
//            get {
//                object obj = ResourceManager.GetObject("dateComeCheckBox.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size dateComeCheckBox_Size {
//            get {
//                object obj = ResourceManager.GetObject("dateComeCheckBox.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int dateComeCheckBox_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("dateComeCheckBox.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 来院日.
//        /// </summary>
//        internal static string dateComeCheckBox_Text {
//            get {
//                return ResourceManager.GetString("dateComeCheckBox.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point dateComeFromDate_Location {
//            get {
//                object obj = ResourceManager.GetObject("dateComeFromDate.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size dateComeFromDate_Size {
//            get {
//                object obj = ResourceManager.GetObject("dateComeFromDate.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int dateComeFromDate_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("dateComeFromDate.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point dateComePanel_Location {
//            get {
//                object obj = ResourceManager.GetObject("dateComePanel.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size dateComePanel_Size {
//            get {
//                object obj = ResourceManager.GetObject("dateComePanel.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int dateComePanel_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("dateComePanel.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point dateComeToDate_Location {
//            get {
//                object obj = ResourceManager.GetObject("dateComeToDate.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size dateComeToDate_Size {
//            get {
//                object obj = ResourceManager.GetObject("dateComeToDate.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int dateComeToDate_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("dateComeToDate.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point diseaseListFilterControl_Location {
//            get {
//                object obj = ResourceManager.GetObject("diseaseListFilterControl.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size diseaseListFilterControl_Size {
//            get {
//                object obj = ResourceManager.GetObject("diseaseListFilterControl.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int diseaseListFilterControl_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("diseaseListFilterControl.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to filterControl1.
//        /// </summary>
//        internal static string diseaseListFilterControl_Text {
//            get {
//                return ResourceManager.GetString("diseaseListFilterControl.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point drugListFilterControl_Location {
//            get {
//                object obj = ResourceManager.GetObject("drugListFilterControl.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size drugListFilterControl_Size {
//            get {
//                object obj = ResourceManager.GetObject("drugListFilterControl.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int drugListFilterControl_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("drugListFilterControl.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to filterControl2.
//        /// </summary>
//        internal static string drugListFilterControl_Text {
//            get {
//                return ResourceManager.GetString("drugListFilterControl.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point familyCondRichTextBox_Location {
//            get {
//                object obj = ResourceManager.GetObject("familyCondRichTextBox.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size familyCondRichTextBox_Size {
//            get {
//                object obj = ResourceManager.GetObject("familyCondRichTextBox.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int familyCondRichTextBox_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("familyCondRichTextBox.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to .
//        /// </summary>
//        internal static string familyCondRichTextBox_Text {
//            get {
//                return ResourceManager.GetString("familyCondRichTextBox.Text", resourceCulture);
//            }
//        }
        
//        internal static bool femaleRadioButton_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("femaleRadioButton.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point femaleRadioButton_Location {
//            get {
//                object obj = ResourceManager.GetObject("femaleRadioButton.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size femaleRadioButton_Size {
//            get {
//                object obj = ResourceManager.GetObject("femaleRadioButton.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int femaleRadioButton_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("femaleRadioButton.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 女性.
//        /// </summary>
//        internal static string femaleRadioButton_Text {
//            get {
//                return ResourceManager.GetString("femaleRadioButton.Text", resourceCulture);
//            }
//        }
        
//        internal static bool genderCheckBox_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("genderCheckBox.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point genderCheckBox_Location {
//            get {
//                object obj = ResourceManager.GetObject("genderCheckBox.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size genderCheckBox_Size {
//            get {
//                object obj = ResourceManager.GetObject("genderCheckBox.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int genderCheckBox_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("genderCheckBox.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 性別.
//        /// </summary>
//        internal static string genderCheckBox_Text {
//            get {
//                return ResourceManager.GetString("genderCheckBox.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point genderPanel_Location {
//            get {
//                object obj = ResourceManager.GetObject("genderPanel.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size genderPanel_Size {
//            get {
//                object obj = ResourceManager.GetObject("genderPanel.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int genderPanel_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("genderPanel.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point grdPatientList_Location {
//            get {
//                object obj = ResourceManager.GetObject("grdPatientList.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Collections.Generic.List<string> grdPatientList_ParamList {
//            get {
//                object obj = ResourceManager.GetObject("grdPatientList.ParamList", resourceCulture);
//                return ((System.Collections.Generic.List<string>)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size grdPatientList_Size {
//            get {
//                object obj = ResourceManager.GetObject("grdPatientList.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int grdPatientList_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("grdPatientList.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point grdPatientListJoin_Location {
//            get {
//                object obj = ResourceManager.GetObject("grdPatientListJoin.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Collections.Generic.List<string> grdPatientListJoin_ParamList {
//            get {
//                object obj = ResourceManager.GetObject("grdPatientListJoin.ParamList", resourceCulture);
//                return ((System.Collections.Generic.List<string>)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size grdPatientListJoin_Size {
//            get {
//                object obj = ResourceManager.GetObject("grdPatientListJoin.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int grdPatientListJoin_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("grdPatientListJoin.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point grdProtocolList_Location {
//            get {
//                object obj = ResourceManager.GetObject("grdProtocolList.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Collections.Generic.List<string> grdProtocolList_ParamList {
//            get {
//                object obj = ResourceManager.GetObject("grdProtocolList.ParamList", resourceCulture);
//                return ((System.Collections.Generic.List<string>)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size grdProtocolList_Size {
//            get {
//                object obj = ResourceManager.GetObject("grdProtocolList.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int grdProtocolList_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("grdProtocolList.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 検体検査結果.
//        /// </summary>
//        internal static string gridColumnCplResult_Caption {
//            get {
//                return ResourceManager.GetString("gridColumnCplResult.Caption", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to DrugHangmogCode.
//        /// </summary>
//        internal static string gridColumnDrugHangmogCode_Caption {
//            get {
//                return ResourceManager.GetString("gridColumnDrugHangmogCode.Caption", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 服薬情報コード.
//        /// </summary>
//        internal static string gridColumnDrugHangmogCode_Caption1 {
//            get {
//                return ResourceManager.GetString("gridColumnDrugHangmogCode.Caption1", resourceCulture);
//            }
//        }
        
//        internal static bool gridColumnDrugHangmogCode_Visible {
//            get {
//                object obj = ResourceManager.GetObject("gridColumnDrugHangmogCode.Visible", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static int gridColumnDrugHangmogCode_VisibleIndex {
//            get {
//                object obj = ResourceManager.GetObject("gridColumnDrugHangmogCode.VisibleIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to OrderHangmogCode.
//        /// </summary>
//        internal static string gridColumnOrderHangmogCode_Caption {
//            get {
//                return ResourceManager.GetString("gridColumnOrderHangmogCode.Caption", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 検査項目コード.
//        /// </summary>
//        internal static string gridColumnOrderHangmogCode_Caption1 {
//            get {
//                return ResourceManager.GetString("gridColumnOrderHangmogCode.Caption1", resourceCulture);
//            }
//        }
        
//        internal static bool gridColumnOrderHangmogCode_Visible {
//            get {
//                object obj = ResourceManager.GetObject("gridColumnOrderHangmogCode.Visible", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static int gridColumnOrderHangmogCode_VisibleIndex {
//            get {
//                object obj = ResourceManager.GetObject("gridColumnOrderHangmogCode.VisibleIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to SangCode.
//        /// </summary>
//        internal static string gridColumnSangCode_Caption {
//            get {
//                return ResourceManager.GetString("gridColumnSangCode.Caption", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 傷病コード.
//        /// </summary>
//        internal static string gridColumnSangCode_Caption1 {
//            get {
//                return ResourceManager.GetString("gridColumnSangCode.Caption1", resourceCulture);
//            }
//        }
        
//        internal static bool gridColumnSangCode_Visible {
//            get {
//                object obj = ResourceManager.GetObject("gridColumnSangCode.Visible", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static int gridColumnSangCode_VisibleIndex {
//            get {
//                object obj = ResourceManager.GetObject("gridColumnSangCode.VisibleIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to SangStartDate.
//        /// </summary>
//        internal static string gridColumnSangStartDate_Caption {
//            get {
//                return ResourceManager.GetString("gridColumnSangStartDate.Caption", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 傷病開始日.
//        /// </summary>
//        internal static string gridColumnSangStartDate_Caption1 {
//            get {
//                return ResourceManager.GetString("gridColumnSangStartDate.Caption1", resourceCulture);
//            }
//        }
        
//        internal static bool gridColumnSangStartDate_Visible {
//            get {
//                object obj = ResourceManager.GetObject("gridColumnSangStartDate.Visible", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static int gridColumnSangStartDate_VisibleIndex {
//            get {
//                object obj = ResourceManager.GetObject("gridColumnSangStartDate.VisibleIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static DevExpress.Utils.DefaultBoolean gridControl1_EmbeddedNavigator_AllowHtmlTextInToolTip {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.EmbeddedNavigator.AllowHtmlTextInToolTip", resourceCulture);
//                return ((DevExpress.Utils.DefaultBoolean)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.AnchorStyles gridControl1_EmbeddedNavigator_Anchor {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.EmbeddedNavigator.Anchor", resourceCulture);
//                return ((System.Windows.Forms.AnchorStyles)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.ImageLayout gridControl1_EmbeddedNavigator_BackgroundImageLayout {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.EmbeddedNavigator.BackgroundImageLayout", resourceCulture);
//                return ((System.Windows.Forms.ImageLayout)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.ImeMode gridControl1_EmbeddedNavigator_ImeMode {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.EmbeddedNavigator.ImeMode", resourceCulture);
//                return ((System.Windows.Forms.ImeMode)(obj));
//            }
//        }
        
//        internal static DevExpress.XtraEditors.NavigatorButtonsTextLocation gridControl1_EmbeddedNavigator_TextLocation {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.EmbeddedNavigator.TextLocation", resourceCulture);
//                return ((DevExpress.XtraEditors.NavigatorButtonsTextLocation)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to .
//        /// </summary>
//        internal static string gridControl1_EmbeddedNavigator_ToolTip {
//            get {
//                return ResourceManager.GetString("gridControl1.EmbeddedNavigator.ToolTip", resourceCulture);
//            }
//        }
        
//        internal static DevExpress.Utils.ToolTipIconType gridControl1_EmbeddedNavigator_ToolTipIconType {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.EmbeddedNavigator.ToolTipIconType", resourceCulture);
//                return ((DevExpress.Utils.ToolTipIconType)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to .
//        /// </summary>
//        internal static string gridControl1_EmbeddedNavigator_ToolTipTitle {
//            get {
//                return ResourceManager.GetString("gridControl1.EmbeddedNavigator.ToolTipTitle", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point gridControl1_Location {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size gridControl1_Size {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int gridControl1_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static bool gridControl1_Visible {
//            get {
//                object obj = ResourceManager.GetObject("gridControl1.Visible", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static DevExpress.Utils.DefaultBoolean gridControl2_EmbeddedNavigator_AllowHtmlTextInToolTip {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.EmbeddedNavigator.AllowHtmlTextInToolTip", resourceCulture);
//                return ((DevExpress.Utils.DefaultBoolean)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.AnchorStyles gridControl2_EmbeddedNavigator_Anchor {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.EmbeddedNavigator.Anchor", resourceCulture);
//                return ((System.Windows.Forms.AnchorStyles)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.ImageLayout gridControl2_EmbeddedNavigator_BackgroundImageLayout {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.EmbeddedNavigator.BackgroundImageLayout", resourceCulture);
//                return ((System.Windows.Forms.ImageLayout)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.ImeMode gridControl2_EmbeddedNavigator_ImeMode {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.EmbeddedNavigator.ImeMode", resourceCulture);
//                return ((System.Windows.Forms.ImeMode)(obj));
//            }
//        }
        
//        internal static DevExpress.XtraEditors.NavigatorButtonsTextLocation gridControl2_EmbeddedNavigator_TextLocation {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.EmbeddedNavigator.TextLocation", resourceCulture);
//                return ((DevExpress.XtraEditors.NavigatorButtonsTextLocation)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to .
//        /// </summary>
//        internal static string gridControl2_EmbeddedNavigator_ToolTip {
//            get {
//                return ResourceManager.GetString("gridControl2.EmbeddedNavigator.ToolTip", resourceCulture);
//            }
//        }
        
//        internal static DevExpress.Utils.ToolTipIconType gridControl2_EmbeddedNavigator_ToolTipIconType {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.EmbeddedNavigator.ToolTipIconType", resourceCulture);
//                return ((DevExpress.Utils.ToolTipIconType)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to .
//        /// </summary>
//        internal static string gridControl2_EmbeddedNavigator_ToolTipTitle {
//            get {
//                return ResourceManager.GetString("gridControl2.EmbeddedNavigator.ToolTipTitle", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point gridControl2_Location {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size gridControl2_Size {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int gridControl2_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static bool gridControl2_Visible {
//            get {
//                object obj = ResourceManager.GetObject("gridControl2.Visible", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static DevExpress.Utils.DefaultBoolean gridControl3_EmbeddedNavigator_AllowHtmlTextInToolTip {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.EmbeddedNavigator.AllowHtmlTextInToolTip", resourceCulture);
//                return ((DevExpress.Utils.DefaultBoolean)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.AnchorStyles gridControl3_EmbeddedNavigator_Anchor {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.EmbeddedNavigator.Anchor", resourceCulture);
//                return ((System.Windows.Forms.AnchorStyles)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.ImageLayout gridControl3_EmbeddedNavigator_BackgroundImageLayout {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.EmbeddedNavigator.BackgroundImageLayout", resourceCulture);
//                return ((System.Windows.Forms.ImageLayout)(obj));
//            }
//        }
        
//        internal static System.Windows.Forms.ImeMode gridControl3_EmbeddedNavigator_ImeMode {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.EmbeddedNavigator.ImeMode", resourceCulture);
//                return ((System.Windows.Forms.ImeMode)(obj));
//            }
//        }
        
//        internal static DevExpress.XtraEditors.NavigatorButtonsTextLocation gridControl3_EmbeddedNavigator_TextLocation {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.EmbeddedNavigator.TextLocation", resourceCulture);
//                return ((DevExpress.XtraEditors.NavigatorButtonsTextLocation)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to .
//        /// </summary>
//        internal static string gridControl3_EmbeddedNavigator_ToolTip {
//            get {
//                return ResourceManager.GetString("gridControl3.EmbeddedNavigator.ToolTip", resourceCulture);
//            }
//        }
        
//        internal static DevExpress.Utils.ToolTipIconType gridControl3_EmbeddedNavigator_ToolTipIconType {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.EmbeddedNavigator.ToolTipIconType", resourceCulture);
//                return ((DevExpress.Utils.ToolTipIconType)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to .
//        /// </summary>
//        internal static string gridControl3_EmbeddedNavigator_ToolTipTitle {
//            get {
//                return ResourceManager.GetString("gridControl3.EmbeddedNavigator.ToolTipTitle", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point gridControl3_Location {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size gridControl3_Size {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int gridControl3_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static bool gridControl3_Visible {
//            get {
//                object obj = ResourceManager.GetObject("gridControl3.Visible", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point ImageList_TrayLocation {
//            get {
//                object obj = ResourceManager.GetObject("ImageList.TrayLocation", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static bool joinedRadioButton_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("joinedRadioButton.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point joinedRadioButton_Location {
//            get {
//                object obj = ResourceManager.GetObject("joinedRadioButton.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size joinedRadioButton_Size {
//            get {
//                object obj = ResourceManager.GetObject("joinedRadioButton.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int joinedRadioButton_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("joinedRadioButton.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to あり.
//        /// </summary>
//        internal static string joinedRadioButton_Text {
//            get {
//                return ResourceManager.GetString("joinedRadioButton.Text", resourceCulture);
//            }
//        }
        
//        internal static bool maleRadioButton_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("maleRadioButton.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point maleRadioButton_Location {
//            get {
//                object obj = ResourceManager.GetObject("maleRadioButton.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size maleRadioButton_Size {
//            get {
//                object obj = ResourceManager.GetObject("maleRadioButton.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int maleRadioButton_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("maleRadioButton.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 男性.
//        /// </summary>
//        internal static string maleRadioButton_Text {
//            get {
//                return ResourceManager.GetString("maleRadioButton.Text", resourceCulture);
//            }
//        }
        
//        internal static bool notJoinedRadioButton_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("notJoinedRadioButton.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point notJoinedRadioButton_Location {
//            get {
//                object obj = ResourceManager.GetObject("notJoinedRadioButton.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size notJoinedRadioButton_Size {
//            get {
//                object obj = ResourceManager.GetObject("notJoinedRadioButton.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int notJoinedRadioButton_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("notJoinedRadioButton.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to なし.
//        /// </summary>
//        internal static string notJoinedRadioButton_Text {
//            get {
//                return ResourceManager.GetString("notJoinedRadioButton.Text", resourceCulture);
//            }
//        }
        
//        internal static bool notUsedRadioButton_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("notUsedRadioButton.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point notUsedRadioButton_Location {
//            get {
//                object obj = ResourceManager.GetObject("notUsedRadioButton.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size notUsedRadioButton_Size {
//            get {
//                object obj = ResourceManager.GetObject("notUsedRadioButton.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int notUsedRadioButton_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("notUsedRadioButton.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to なし.
//        /// </summary>
//        internal static string notUsedRadioButton_Text {
//            get {
//                return ResourceManager.GetString("notUsedRadioButton.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point orderListFilterControl_Location {
//            get {
//                object obj = ResourceManager.GetObject("orderListFilterControl.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size orderListFilterControl_Size {
//            get {
//                object obj = ResourceManager.GetObject("orderListFilterControl.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int orderListFilterControl_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("orderListFilterControl.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to filterControl3.
//        /// </summary>
//        internal static string orderListFilterControl_Text {
//            get {
//                return ResourceManager.GetString("orderListFilterControl.Text", resourceCulture);
//            }
//        }
        
//        internal static bool pacerMakerCheckBox_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("pacerMakerCheckBox.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point pacerMakerCheckBox_Location {
//            get {
//                object obj = ResourceManager.GetObject("pacerMakerCheckBox.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size pacerMakerCheckBox_Size {
//            get {
//                object obj = ResourceManager.GetObject("pacerMakerCheckBox.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int pacerMakerCheckBox_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("pacerMakerCheckBox.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to ベースメーカー.
//        /// </summary>
//        internal static string pacerMakerCheckBox_Text {
//            get {
//                return ResourceManager.GetString("pacerMakerCheckBox.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point pacermakerPanel_Location {
//            get {
//                object obj = ResourceManager.GetObject("pacermakerPanel.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size pacermakerPanel_Size {
//            get {
//                object obj = ResourceManager.GetObject("pacermakerPanel.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int pacermakerPanel_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("pacermakerPanel.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point searchButton_Location {
//            get {
//                object obj = ResourceManager.GetObject("searchButton.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size searchButton_Size {
//            get {
//                object obj = ResourceManager.GetObject("searchButton.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int searchButton_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("searchButton.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 検索.
//        /// </summary>
//        internal static string searchButton_Text {
//            get {
//                return ResourceManager.GetString("searchButton.Text", resourceCulture);
//            }
//        }
        
//        internal static bool usedRadioButton_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("usedRadioButton.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point usedRadioButton_Location {
//            get {
//                object obj = ResourceManager.GetObject("usedRadioButton.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size usedRadioButton_Size {
//            get {
//                object obj = ResourceManager.GetObject("usedRadioButton.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int usedRadioButton_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("usedRadioButton.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to あり.
//        /// </summary>
//        internal static string usedRadioButton_Text {
//            get {
//                return ResourceManager.GetString("usedRadioButton.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point xButtonList1_Location {
//            get {
//                object obj = ResourceManager.GetObject("xButtonList1.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static int xButtonList1_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xButtonList1.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 選択.
//        /// </summary>
//        internal static string xEditGridCell1_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell1.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to protocol_id.
//        /// </summary>
//        internal static string xEditGridCell10_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell10.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 参加患者番号.
//        /// </summary>
//        internal static string xEditGridCell2_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell2.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 参加患者名.
//        /// </summary>
//        internal static string xEditGridCell3_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell3.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 年齢.
//        /// </summary>
//        internal static string xEditGridCell4_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell4.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 性別.
//        /// </summary>
//        internal static string xEditGridCell5_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell5.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 治験ID.
//        /// </summary>
//        internal static string xEditGridCell6_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell6.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 治験名.
//        /// </summary>
//        internal static string xEditGridCell7_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell7.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 参加患者番号.
//        /// </summary>
//        internal static string xEditGridCell8_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell8.HeaderText", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 参加患者名.
//        /// </summary>
//        internal static string xEditGridCell9_HeaderText {
//            get {
//                return ResourceManager.GetString("xEditGridCell9.HeaderText", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point xGroupBox1_Location {
//            get {
//                object obj = ResourceManager.GetObject("xGroupBox1.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size xGroupBox1_Size {
//            get {
//                object obj = ResourceManager.GetObject("xGroupBox1.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int xGroupBox1_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xGroupBox1.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 基本.
//        /// </summary>
//        internal static string xGroupBox1_Text {
//            get {
//                return ResourceManager.GetString("xGroupBox1.Text", resourceCulture);
//            }
//        }
        
//        internal static System.Drawing.Point xGroupBox2_Location {
//            get {
//                object obj = ResourceManager.GetObject("xGroupBox2.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size xGroupBox2_Size {
//            get {
//                object obj = ResourceManager.GetObject("xGroupBox2.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int xGroupBox2_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xGroupBox2.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 詳細.
//        /// </summary>
//        internal static string xGroupBox2_Text {
//            get {
//                return ResourceManager.GetString("xGroupBox2.Text", resourceCulture);
//            }
//        }
        
//        internal static bool xLabel1_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("xLabel1.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point xLabel1_Location {
//            get {
//                object obj = ResourceManager.GetObject("xLabel1.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size xLabel1_Size {
//            get {
//                object obj = ResourceManager.GetObject("xLabel1.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int xLabel1_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xLabel1.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to ～.
//        /// </summary>
//        internal static string xLabel1_Text {
//            get {
//                return ResourceManager.GetString("xLabel1.Text", resourceCulture);
//            }
//        }
        
//        internal static bool xLabel2_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("xLabel2.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point xLabel2_Location {
//            get {
//                object obj = ResourceManager.GetObject("xLabel2.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size xLabel2_Size {
//            get {
//                object obj = ResourceManager.GetObject("xLabel2.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int xLabel2_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xLabel2.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to ～.
//        /// </summary>
//        internal static string xLabel2_Text {
//            get {
//                return ResourceManager.GetString("xLabel2.Text", resourceCulture);
//            }
//        }
        
//        internal static bool xLabel3_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("xLabel3.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point xLabel3_Location {
//            get {
//                object obj = ResourceManager.GetObject("xLabel3.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size xLabel3_Size {
//            get {
//                object obj = ResourceManager.GetObject("xLabel3.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int xLabel3_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xLabel3.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 傷病.
//        /// </summary>
//        internal static string xLabel3_Text {
//            get {
//                return ResourceManager.GetString("xLabel3.Text", resourceCulture);
//            }
//        }
        
//        internal static bool xLabel4_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("xLabel4.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point xLabel4_Location {
//            get {
//                object obj = ResourceManager.GetObject("xLabel4.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size xLabel4_Size {
//            get {
//                object obj = ResourceManager.GetObject("xLabel4.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int xLabel4_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xLabel4.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 服薬情報.
//        /// </summary>
//        internal static string xLabel4_Text {
//            get {
//                return ResourceManager.GetString("xLabel4.Text", resourceCulture);
//            }
//        }
        
//        internal static bool xLabel5_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("xLabel5.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point xLabel5_Location {
//            get {
//                object obj = ResourceManager.GetObject("xLabel5.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size xLabel5_Size {
//            get {
//                object obj = ResourceManager.GetObject("xLabel5.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int xLabel5_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xLabel5.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 検査結果.
//        /// </summary>
//        internal static string xLabel5_Text {
//            get {
//                return ResourceManager.GetString("xLabel5.Text", resourceCulture);
//            }
//        }
        
//        internal static bool xLabel6_AutoSize {
//            get {
//                object obj = ResourceManager.GetObject("xLabel6.AutoSize", resourceCulture);
//                return ((bool)(obj));
//            }
//        }
        
//        internal static System.Drawing.Point xLabel6_Location {
//            get {
//                object obj = ResourceManager.GetObject("xLabel6.Location", resourceCulture);
//                return ((System.Drawing.Point)(obj));
//            }
//        }
        
//        internal static System.Drawing.Size xLabel6_Size {
//            get {
//                object obj = ResourceManager.GetObject("xLabel6.Size", resourceCulture);
//                return ((System.Drawing.Size)(obj));
//            }
//        }
        
//        internal static int xLabel6_TabIndex {
//            get {
//                object obj = ResourceManager.GetObject("xLabel6.TabIndex", resourceCulture);
//                return ((int)(obj));
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to 家族歴.
//        /// </summary>
//        internal static string xLabel6_Text {
//            get {
//                return ResourceManager.GetString("xLabel6.Text", resourceCulture);
//            }
//        }
//    }
//}
