//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadGridBIL2016U02Info")]
  public partial class LoadGridBIL2016U02Info : global::ProtoBuf.IExtensible
  {
    public LoadGridBIL2016U02Info() {}
    
    private string _hangmog_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hangmog_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_code
    {
      get { return _hangmog_code; }
      set { _hangmog_code = value; }
    }
    private string _hangmog_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hangmog_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_name
    {
      get { return _hangmog_name; }
      set { _hangmog_name = value; }
    }
    private string _unit = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"unit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string unit
    {
      get { return _unit; }
      set { _unit = value; }
    }
    private string _price = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string price
    {
      get { return _price; }
      set { _price = value; }
    }
    private string _quantity = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }
    private string _amount = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private string _insurance_pay = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"insurance_pay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string insurance_pay
    {
      get { return _insurance_pay; }
      set { _insurance_pay = value; }
    }
    private string _patient_pay = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"patient_pay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string patient_pay
    {
      get { return _patient_pay; }
      set { _patient_pay = value; }
    }
    private string _discount = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"discount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string discount
    {
      get { return _discount; }
      set { _discount = value; }
    }
    private string _dept_req_cd = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dept_req_cd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dept_req_cd
    {
      get { return _dept_req_cd; }
      set { _dept_req_cd = value; }
    }
    private string _dept_req_nm = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"dept_req_nm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dept_req_nm
    {
      get { return _dept_req_nm; }
      set { _dept_req_nm = value; }
    }
    private string _doctor_req_cd = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"doctor_req_cd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_req_cd
    {
      get { return _doctor_req_cd; }
      set { _doctor_req_cd = value; }
    }
    private string _doctor_req_nm = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"doctor_req_nm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_req_nm
    {
      get { return _doctor_req_nm; }
      set { _doctor_req_nm = value; }
    }
    private string _dept_exc_cd = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"dept_exc_cd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dept_exc_cd
    {
      get { return _dept_exc_cd; }
      set { _dept_exc_cd = value; }
    }
    private string _dept_exc_nm = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"dept_exc_nm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dept_exc_nm
    {
      get { return _dept_exc_nm; }
      set { _dept_exc_nm = value; }
    }
    private string _doctor_exc_cd = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"doctor_exc_cd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_exc_cd
    {
      get { return _doctor_exc_cd; }
      set { _doctor_exc_cd = value; }
    }
    private string _doctor_exc_nm = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"doctor_exc_nm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_exc_nm
    {
      get { return _doctor_exc_nm; }
      set { _doctor_exc_nm = value; }
    }
    private string _order_group_cd = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"order_group_cd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_group_cd
    {
      get { return _order_group_cd; }
      set { _order_group_cd = value; }
    }
    private string _order_group_nm = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"order_group_nm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_group_nm
    {
      get { return _order_group_nm; }
      set { _order_group_nm = value; }
    }
    private string _order_date = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"order_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_date
    {
      get { return _order_date; }
      set { _order_date = value; }
    }
    private string _acting_date = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"acting_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string acting_date
    {
      get { return _acting_date; }
      set { _acting_date = value; }
    }
    private string _discount_reason = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"discount_reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string discount_reason
    {
      get { return _discount_reason; }
      set { _discount_reason = value; }
    }
    private string _check_yn = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"check_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string check_yn
    {
      get { return _check_yn; }
      set { _check_yn = value; }
    }
    private string _fkocs1003 = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"fkocs1003", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fkocs1003
    {
      get { return _fkocs1003; }
      set { _fkocs1003 = value; }
    }
    private string _amount_paid = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"amount_paid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string amount_paid
    {
      get { return _amount_paid; }
      set { _amount_paid = value; }
    }
    private string _amount_debt = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"amount_debt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string amount_debt
    {
      get { return _amount_debt; }
      set { _amount_debt = value; }
    }
    private string _fkout1001 = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"fkout1001", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fkout1001
    {
      get { return _fkout1001; }
      set { _fkout1001 = value; }
    }
    private string _patient_address = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"patient_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string patient_address
    {
      get { return _patient_address; }
      set { _patient_address = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
