//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS0103U10SetTabWonnaeDrgInfo")]
  public partial class OCS0103U10SetTabWonnaeDrgInfo : global::ProtoBuf.IExtensible
  {
    public OCS0103U10SetTabWonnaeDrgInfo() {}
    
    private string _filter = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string filter
    {
      get { return _filter; }
      set { _filter = value; }
    }
    private string _cnt = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cnt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cnt
    {
      get { return _cnt; }
      set { _cnt = value; }
    }
    private string _yak_kijun_code = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"yak_kijun_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string yak_kijun_code
    {
      get { return _yak_kijun_code; }
      set { _yak_kijun_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
