//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS3003Q10GrdOrderListItemInfo")]
  public partial class OCS3003Q10GrdOrderListItemInfo : global::ProtoBuf.IExtensible
  {
    public OCS3003Q10GrdOrderListItemInfo() {}
    
    private string _input_gubun_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_gubun_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_gubun_name
    {
      get { return _input_gubun_name; }
      set { _input_gubun_name = value; }
    }
    private string _group_ser = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"group_ser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string group_ser
    {
      get { return _group_ser; }
      set { _group_ser = value; }
    }
    private string _order_gubun_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"order_gubun_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_gubun_name
    {
      get { return _order_gubun_name; }
      set { _order_gubun_name = value; }
    }
    private string _hangmog_code = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hangmog_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_code
    {
      get { return _hangmog_code; }
      set { _hangmog_code = value; }
    }
    private string _hangmog_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hangmog_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_name
    {
      get { return _hangmog_name; }
      set { _hangmog_name = value; }
    }
    private string _suryang = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"suryang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suryang
    {
      get { return _suryang; }
      set { _suryang = value; }
    }
    private string _ord_danui = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ord_danui", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ord_danui
    {
      get { return _ord_danui; }
      set { _ord_danui = value; }
    }
    private string _ord_danui_name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ord_danui_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ord_danui_name
    {
      get { return _ord_danui_name; }
      set { _ord_danui_name = value; }
    }
    private string _dv_time = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"dv_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_time
    {
      get { return _dv_time; }
      set { _dv_time = value; }
    }
    private string _dv = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv
    {
      get { return _dv; }
      set { _dv = value; }
    }
    private string _nalsu = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"nalsu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nalsu
    {
      get { return _nalsu; }
      set { _nalsu = value; }
    }
    private string _wonyoi_order_yn = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"wonyoi_order_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonyoi_order_yn
    {
      get { return _wonyoi_order_yn; }
      set { _wonyoi_order_yn = value; }
    }
    private string _emergency = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"emergency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string emergency
    {
      get { return _emergency; }
      set { _emergency = value; }
    }
    private string _pay = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"pay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pay
    {
      get { return _pay; }
      set { _pay = value; }
    }
    private string _anti_cancer_yn = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"anti_cancer_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string anti_cancer_yn
    {
      get { return _anti_cancer_yn; }
      set { _anti_cancer_yn = value; }
    }
    private string _muhyo = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"muhyo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string muhyo
    {
      get { return _muhyo; }
      set { _muhyo = value; }
    }
    private string _portable_yn = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"portable_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portable_yn
    {
      get { return _portable_yn; }
      set { _portable_yn = value; }
    }
    private string _ocs_flag = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"ocs_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ocs_flag
    {
      get { return _ocs_flag; }
      set { _ocs_flag = value; }
    }
    private string _order_gubun = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"order_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_gubun
    {
      get { return _order_gubun; }
      set { _order_gubun = value; }
    }
    private string _input_tab = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"input_tab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_tab
    {
      get { return _input_tab; }
      set { _input_tab = value; }
    }
    private string _input_gubun = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"input_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_gubun
    {
      get { return _input_gubun; }
      set { _input_gubun = value; }
    }
    private string _after_act_yn = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"after_act_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string after_act_yn
    {
      get { return _after_act_yn; }
      set { _after_act_yn = value; }
    }
    private string _jundal_table = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"jundal_table", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_table
    {
      get { return _jundal_table; }
      set { _jundal_table = value; }
    }
    private string _jundal_part = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"jundal_part", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_part
    {
      get { return _jundal_part; }
      set { _jundal_part = value; }
    }
    private string _move_part = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"move_part", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string move_part
    {
      get { return _move_part; }
      set { _move_part = value; }
    }
    private string _bunho = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _naewon_date = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"naewon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string naewon_date
    {
      get { return _naewon_date; }
      set { _naewon_date = value; }
    }
    private string _gwa = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"gwa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gwa
    {
      get { return _gwa; }
      set { _gwa = value; }
    }
    private string _doctor = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"doctor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor
    {
      get { return _doctor; }
      set { _doctor = value; }
    }
    private string _naewon_type = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"naewon_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string naewon_type
    {
      get { return _naewon_type; }
      set { _naewon_type = value; }
    }
    private string _pk_order = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"pk_order", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pk_order
    {
      get { return _pk_order; }
      set { _pk_order = value; }
    }
    private string _seq = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private string _pkocs1003 = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"pkocs1003", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pkocs1003
    {
      get { return _pkocs1003; }
      set { _pkocs1003 = value; }
    }
    private string _sub_susul = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"sub_susul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sub_susul
    {
      get { return _sub_susul; }
      set { _sub_susul = value; }
    }
    private string _sutak_yn = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"sutak_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sutak_yn
    {
      get { return _sutak_yn; }
      set { _sutak_yn = value; }
    }
    private string _amt = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"amt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string amt
    {
      get { return _amt; }
      set { _amt = value; }
    }
    private string _dv_1 = "";
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"dv_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_1
    {
      get { return _dv_1; }
      set { _dv_1 = value; }
    }
    private string _dv_2 = "";
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"dv_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_2
    {
      get { return _dv_2; }
      set { _dv_2 = value; }
    }
    private string _dv_3 = "";
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"dv_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_3
    {
      get { return _dv_3; }
      set { _dv_3 = value; }
    }
    private string _dv_4 = "";
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"dv_4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_4
    {
      get { return _dv_4; }
      set { _dv_4 = value; }
    }
    private string _order_remark = "";
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"order_remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_remark
    {
      get { return _order_remark; }
      set { _order_remark = value; }
    }
    private string _mix_group = "";
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"mix_group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mix_group
    {
      get { return _mix_group; }
      set { _mix_group = value; }
    }
    private string _jubsu_date = "";
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"jubsu_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jubsu_date
    {
      get { return _jubsu_date; }
      set { _jubsu_date = value; }
    }
    private string _acting_date = "";
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"acting_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string acting_date
    {
      get { return _acting_date; }
      set { _acting_date = value; }
    }
    private string _result_date = "";
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"result_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string result_date
    {
      get { return _result_date; }
      set { _result_date = value; }
    }
    private string _dc_gubun = "";
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"dc_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dc_gubun
    {
      get { return _dc_gubun; }
      set { _dc_gubun = value; }
    }
    private string _dc_yn = "";
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"dc_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dc_yn
    {
      get { return _dc_yn; }
      set { _dc_yn = value; }
    }
    private string _bannab_yn = "";
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"bannab_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bannab_yn
    {
      get { return _bannab_yn; }
      set { _bannab_yn = value; }
    }
    private string _donbok_yn = "";
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"donbok_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string donbok_yn
    {
      get { return _donbok_yn; }
      set { _donbok_yn = value; }
    }
    private string _dv_name = "";
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"dv_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_name
    {
      get { return _dv_name; }
      set { _dv_name = value; }
    }
    private string _confirm_check = "";
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"confirm_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string confirm_check
    {
      get { return _confirm_check; }
      set { _confirm_check = value; }
    }
    private string _sunab_check = "";
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"sunab_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sunab_check
    {
      get { return _sunab_check; }
      set { _sunab_check = value; }
    }
    private string _dc_check = "";
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"dc_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dc_check
    {
      get { return _dc_check; }
      set { _dc_check = value; }
    }
    private string _slip_code = "";
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"slip_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string slip_code
    {
      get { return _slip_code; }
      set { _slip_code = value; }
    }
    private string _group_yn = "";
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"group_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string group_yn
    {
      get { return _group_yn; }
      set { _group_yn = value; }
    }
    private string _sg_code = "";
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"sg_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sg_code
    {
      get { return _sg_code; }
      set { _sg_code = value; }
    }
    private string _order_gubun_bas = "";
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"order_gubun_bas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_gubun_bas
    {
      get { return _order_gubun_bas; }
      set { _order_gubun_bas = value; }
    }
    private string _input_control = "";
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"input_control", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_control
    {
      get { return _input_control; }
      set { _input_control = value; }
    }
    private string _suga_yn = "";
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"suga_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suga_yn
    {
      get { return _suga_yn; }
      set { _suga_yn = value; }
    }
    private string _emergency_check = "";
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"emergency_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string emergency_check
    {
      get { return _emergency_check; }
      set { _emergency_check = value; }
    }
    private string _limit_suryang = "";
    [global::ProtoBuf.ProtoMember(61, IsRequired = false, Name=@"limit_suryang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string limit_suryang
    {
      get { return _limit_suryang; }
      set { _limit_suryang = value; }
    }
    private string _specimen_yn = "";
    [global::ProtoBuf.ProtoMember(62, IsRequired = false, Name=@"specimen_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specimen_yn
    {
      get { return _specimen_yn; }
      set { _specimen_yn = value; }
    }
    private string _jaeryo_yn = "";
    [global::ProtoBuf.ProtoMember(63, IsRequired = false, Name=@"jaeryo_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_yn
    {
      get { return _jaeryo_yn; }
      set { _jaeryo_yn = value; }
    }
    private string _ord_danui_check = "";
    [global::ProtoBuf.ProtoMember(64, IsRequired = false, Name=@"ord_danui_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ord_danui_check
    {
      get { return _ord_danui_check; }
      set { _ord_danui_check = value; }
    }
    private string _ord_danui_bas = "";
    [global::ProtoBuf.ProtoMember(65, IsRequired = false, Name=@"ord_danui_bas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ord_danui_bas
    {
      get { return _ord_danui_bas; }
      set { _ord_danui_bas = value; }
    }
    private string _jundal_table_out = "";
    [global::ProtoBuf.ProtoMember(66, IsRequired = false, Name=@"jundal_table_out", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_table_out
    {
      get { return _jundal_table_out; }
      set { _jundal_table_out = value; }
    }
    private string _jundal_part_out = "";
    [global::ProtoBuf.ProtoMember(67, IsRequired = false, Name=@"jundal_part_out", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_part_out
    {
      get { return _jundal_part_out; }
      set { _jundal_part_out = value; }
    }
    private string _bulyong_check = "";
    [global::ProtoBuf.ProtoMember(68, IsRequired = false, Name=@"bulyong_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bulyong_check
    {
      get { return _bulyong_check; }
      set { _bulyong_check = value; }
    }
    private string _wonyoi_order_cr_yn = "";
    [global::ProtoBuf.ProtoMember(69, IsRequired = false, Name=@"wonyoi_order_cr_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonyoi_order_cr_yn
    {
      get { return _wonyoi_order_cr_yn; }
      set { _wonyoi_order_cr_yn = value; }
    }
    private string _default_wonyoi_order_yn = "";
    [global::ProtoBuf.ProtoMember(70, IsRequired = false, Name=@"default_wonyoi_order_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string default_wonyoi_order_yn
    {
      get { return _default_wonyoi_order_yn; }
      set { _default_wonyoi_order_yn = value; }
    }
    private string _nday_yn = "";
    [global::ProtoBuf.ProtoMember(71, IsRequired = false, Name=@"nday_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nday_yn
    {
      get { return _nday_yn; }
      set { _nday_yn = value; }
    }
    private string _muhyo_yn = "";
    [global::ProtoBuf.ProtoMember(72, IsRequired = false, Name=@"muhyo_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string muhyo_yn
    {
      get { return _muhyo_yn; }
      set { _muhyo_yn = value; }
    }
    private string _tel_yn = "";
    [global::ProtoBuf.ProtoMember(73, IsRequired = false, Name=@"tel_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tel_yn
    {
      get { return _tel_yn; }
      set { _tel_yn = value; }
    }
    private string _jundal_part_name = "";
    [global::ProtoBuf.ProtoMember(74, IsRequired = false, Name=@"jundal_part_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_part_name
    {
      get { return _jundal_part_name; }
      set { _jundal_part_name = value; }
    }
    private string _bun_code = "";
    [global::ProtoBuf.ProtoMember(75, IsRequired = false, Name=@"bun_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bun_code
    {
      get { return _bun_code; }
      set { _bun_code = value; }
    }
    private string _drg_info = "";
    [global::ProtoBuf.ProtoMember(76, IsRequired = false, Name=@"drg_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string drg_info
    {
      get { return _drg_info; }
      set { _drg_info = value; }
    }
    private string _drg_bunryu = "";
    [global::ProtoBuf.ProtoMember(77, IsRequired = false, Name=@"drg_bunryu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string drg_bunryu
    {
      get { return _drg_bunryu; }
      set { _drg_bunryu = value; }
    }
    private string _child_gubun = "";
    [global::ProtoBuf.ProtoMember(78, IsRequired = false, Name=@"child_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string child_gubun
    {
      get { return _child_gubun; }
      set { _child_gubun = value; }
    }
    private string _bom_source_key = "";
    [global::ProtoBuf.ProtoMember(79, IsRequired = false, Name=@"bom_source_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bom_source_key
    {
      get { return _bom_source_key; }
      set { _bom_source_key = value; }
    }
    private string _bom_occur_yn = "";
    [global::ProtoBuf.ProtoMember(80, IsRequired = false, Name=@"bom_occur_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bom_occur_yn
    {
      get { return _bom_occur_yn; }
      set { _bom_occur_yn = value; }
    }
    private string _acting_time = "";
    [global::ProtoBuf.ProtoMember(81, IsRequired = false, Name=@"acting_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string acting_time
    {
      get { return _acting_time; }
      set { _acting_time = value; }
    }
    private string _cont_key = "";
    [global::ProtoBuf.ProtoMember(82, IsRequired = false, Name=@"cont_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cont_key
    {
      get { return _cont_key; }
      set { _cont_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
