//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"INV6002U00GrdINV6002Response")]
  public partial class INV6002U00GrdINV6002Response : global::ProtoBuf.IExtensible
  {
    public INV6002U00GrdINV6002Response() {}
    
    private readonly global::System.Collections.Generic.List<INV6002U00GrdINV6002Info> _grd_item = new global::System.Collections.Generic.List<INV6002U00GrdINV6002Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grd_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<INV6002U00GrdINV6002Info> grd_item
    {
      get { return _grd_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
