//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"INV6002U00GrdINV6002Request")]
  public partial class INV6002U00GrdINV6002Request : global::ProtoBuf.IExtensible
  {
    public INV6002U00GrdINV6002Request() {}
    
    private string _gubun = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gubun
    {
      get { return _gubun; }
      set { _gubun = value; }
    }
    private string _hosp_code = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hosp_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hosp_code
    {
      get { return _hosp_code; }
      set { _hosp_code = value; }
    }
    private string _month = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"month", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string month
    {
      get { return _month; }
      set { _month = value; }
    }
    private string _jaeryo_gubun = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"jaeryo_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_gubun
    {
      get { return _jaeryo_gubun; }
      set { _jaeryo_gubun = value; }
    }
    private string _magam_month = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"magam_month", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string magam_month
    {
      get { return _magam_month; }
      set { _magam_month = value; }
    }
    private string _page_number = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"page_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string page_number
    {
      get { return _page_number; }
      set { _page_number = value; }
    }
    private string _offset = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private string _jaeryo_code = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"jaeryo_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_code
    {
      get { return _jaeryo_code; }
      set { _jaeryo_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
