//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: system_service.proto

namespace IHIS.CloudConnector.Messaging
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MainMenuItemInfo")]
    public partial class MainMenuItemInfo : global::ProtoBuf.IExtensible
    {
        public MainMenuItemInfo() { }

        private string _group_id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"group_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string group_id
        {
            get { return _group_id; }
            set { _group_id = value; }
        }
        private string _group_name;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"group_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string group_name
        {
            get { return _group_name; }
            set { _group_name = value; }
        }
        private string _system_id;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"system_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string system_id
        {
            get { return _system_id; }
            set { _system_id = value; }
        }
        private string _system_name;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"system_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string system_name
        {
            get { return _system_name; }
            set { _system_name = value; }
        }
        private string _display_group_id = "";
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"display_group_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string display_group_id
        {
            get { return _display_group_id; }
            set { _display_group_id = value; }
        }
        private string _display_group_name = "";
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"display_group_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string display_group_name
        {
            get { return _display_group_name; }
            set { _display_group_name = value; }
        }
        private string _description = "";
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string description
        {
            get { return _description; }
            set { _description = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
}