//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NUR2016U02GrdListResponse")]
  public partial class NUR2016U02GrdListResponse : global::ProtoBuf.IExtensible
  {
    public NUR2016U02GrdListResponse() {}
    
    private readonly global::System.Collections.Generic.List<NUR2016U02GrdListInfo> _grd_item = new global::System.Collections.Generic.List<NUR2016U02GrdListInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grd_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NUR2016U02GrdListInfo> grd_item
    {
      get { return _grd_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
