//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NUR2016Q00CreateTempIDRequest")]
  public partial class NUR2016Q00CreateTempIDRequest : global::ProtoBuf.IExtensible
  {
    public NUR2016Q00CreateTempIDRequest() {}
    
    private NUR2016Q00CreateTempIDInfo _temp_item = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"temp_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NUR2016Q00CreateTempIDInfo temp_item
    {
      get { return _temp_item; }
      set { _temp_item = value; }
    }
    private bool _orca_patient;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"orca_patient", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool orca_patient
    {
      get { return _orca_patient; }
      set { _orca_patient = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
