//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuro_service.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NuroOUT0101U02GetTypeRequest")]
  public partial class NuroOUT0101U02GetTypeRequest : global::ProtoBuf.IExtensible
  {
    public NuroOUT0101U02GetTypeRequest() {}
    
    private string _johap_gubun = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"johap_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string johap_gubun
    {
      get { return _johap_gubun; }
      set { _johap_gubun = value; }
    }
    private string _find1 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"find1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string find1
    {
      get { return _find1; }
      set { _find1 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
