//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
// Note: requires additional types generated from: nuro_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NuroPatientGridViewResponse")]
  public partial class NuroPatientGridViewResponse : global::ProtoBuf.IExtensible
  {
    public NuroPatientGridViewResponse() {}
    
    private readonly global::System.Collections.Generic.List<NuroPatientCommentListItemInfo> _grdComment_list = new global::System.Collections.Generic.List<NuroPatientCommentListItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grdComment_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NuroPatientCommentListItemInfo> grdComment_list
    {
      get { return _grdComment_list; }
    }
  
    private readonly global::System.Collections.Generic.List<NuroPatientInsuranceListItemInfo> _grdGongbiCode_list = new global::System.Collections.Generic.List<NuroPatientInsuranceListItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"grdGongbiCode_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NuroPatientInsuranceListItemInfo> grdGongbiCode_list
    {
      get { return _grdGongbiCode_list; }
    }
  
    private readonly global::System.Collections.Generic.List<NuroPatientDetailListItemInfo> _grdJubsu_list = new global::System.Collections.Generic.List<NuroPatientDetailListItemInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"grdJubsu_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NuroPatientDetailListItemInfo> grdJubsu_list
    {
      get { return _grdJubsu_list; }
    }
  
    private readonly global::System.Collections.Generic.List<NuroPatientReceptionHistoryListItemInfo> _grdJubsuHistory_list = new global::System.Collections.Generic.List<NuroPatientReceptionHistoryListItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"grdJubsuHistory_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NuroPatientReceptionHistoryListItemInfo> grdJubsuHistory_list
    {
      get { return _grdJubsuHistory_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
