//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuro_service.proto
// Note: requires additional types generated from: nuro_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NuroOUT1001U01GetDbMaxJubsuNoRequest")]
  public partial class NuroOUT1001U01GetDbMaxJubsuNoRequest : global::ProtoBuf.IExtensible
  {
    public NuroOUT1001U01GetDbMaxJubsuNoRequest() {}
    
    private string _bunho;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _naewon_date;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"naewon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string naewon_date
    {
      get { return _naewon_date; }
      set { _naewon_date = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
