//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuro_service.proto
// Note: requires additional types generated from: nuro_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NuroOUT1001U01LoadOUT0105Request")]
  public partial class NuroOUT1001U01LoadOUT0105Request : global::ProtoBuf.IExtensible
  {
    public NuroOUT1001U01LoadOUT0105Request() {}
    
    private string _gongbi_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gongbi_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gongbi_code
    {
      get { return _gongbi_code; }
      set { _gongbi_code = value; }
    }
    private string _fkout1001;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fkout1001", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fkout1001
    {
      get { return _fkout1001; }
      set { _fkout1001 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
