//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ORDERTRANSAPITransferOrdersResponse")]
  public partial class ORDERTRANSAPITransferOrdersResponse : global::ProtoBuf.IExtensible
  {
    public ORDERTRANSAPITransferOrdersResponse() {}
    
    private ORDERTRANSAPIMsgInfo _msg_item = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ORDERTRANSAPIMsgInfo msg_item
    {
      get { return _msg_item; }
      set { _msg_item = value; }
    }
    private readonly global::System.Collections.Generic.List<ORDERTRANSAPIHangmogInfo> _hangmog_err_item = new global::System.Collections.Generic.List<ORDERTRANSAPIHangmogInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hangmog_err_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ORDERTRANSAPIHangmogInfo> hangmog_err_item
    {
      get { return _hangmog_err_item; }
    }
  
    private readonly global::System.Collections.Generic.List<MedicalInformation> _medical_info_item = new global::System.Collections.Generic.List<MedicalInformation>();
    [global::ProtoBuf.ProtoMember(3, Name=@"medical_info_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MedicalInformation> medical_info_item
    {
      get { return _medical_info_item; }
    }
  
    private string _dept_code = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dept_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dept_code
    {
      get { return _dept_code; }
      set { _dept_code = value; }
    }
    private string _physician_code = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"physician_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string physician_code
    {
      get { return _physician_code; }
      set { _physician_code = value; }
    }
    private string _doctor_fee = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"doctor_fee", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_fee
    {
      get { return _doctor_fee; }
      set { _doctor_fee = value; }
    }
    private string _insurance_combination_number = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"insurance_combination_number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string insurance_combination_number
    {
      get { return _insurance_combination_number; }
      set { _insurance_combination_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
