//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service2.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OUT0101Q01GrdPatientListResponse")]
  public partial class OUT0101Q01GrdPatientListResponse : global::ProtoBuf.IExtensible
  {
    public OUT0101Q01GrdPatientListResponse() {}
    
    private readonly global::System.Collections.Generic.List<OUT0101Q01GrdPatientListInfo> _item = new global::System.Collections.Generic.List<OUT0101Q01GrdPatientListInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OUT0101Q01GrdPatientListInfo> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
