//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuro_service.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RES1001U00ReservationScheduleListGroupedResponse")]
  public partial class RES1001U00ReservationScheduleListGroupedResponse : global::ProtoBuf.IExtensible
  {
    public RES1001U00ReservationScheduleListGroupedResponse() {}
    
    private readonly global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleConditionListItemInfo> _res_schedule_condition_list_item = new global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleConditionListItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"res_schedule_condition_list_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleConditionListItemInfo> res_schedule_condition_list_item
    {
      get { return _res_schedule_condition_list_item; }
    }
  
    private readonly global::System.Collections.Generic.List<NuroRES1001U00AverageTimeListItemInfo> _avg_time_list_item = new global::System.Collections.Generic.List<NuroRES1001U00AverageTimeListItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"avg_time_list_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NuroRES1001U00AverageTimeListItemInfo> avg_time_list_item
    {
      get { return _avg_time_list_item; }
    }
  
    private readonly global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleListItemInfo> _res_schedule_am_list_item = new global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleListItemInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"res_schedule_am_list_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleListItemInfo> res_schedule_am_list_item
    {
      get { return _res_schedule_am_list_item; }
    }
  
    private readonly global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleListItemInfo> _res_schedule_pm_list_item = new global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleListItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"res_schedule_pm_list_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NuroRES1001U00ReservationScheduleListItemInfo> res_schedule_pm_list_item
    {
      get { return _res_schedule_pm_list_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
