//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuts_service.proto
// Note: requires additional types generated from: nuts_model.proto
// Note: requires additional types generated from: system_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NUT0001U00InitializeScreenRequest")]
  public partial class NUT0001U00InitializeScreenRequest : global::ProtoBuf.IExtensible
  {
    public NUT0001U00InitializeScreenRequest() {}
    
    private string _doctor_gwa_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"doctor_gwa_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_gwa_name
    {
      get { return _doctor_gwa_name; }
      set { _doctor_gwa_name = value; }
    }
    private string _gwa_code = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gwa_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gwa_code
    {
      get { return _gwa_code; }
      set { _gwa_code = value; }
    }
    private string _pkocskey = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pkocskey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pkocskey
    {
      get { return _pkocskey; }
      set { _pkocskey = value; }
    }
    private string _in_out_gubun = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"in_out_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string in_out_gubun
    {
      get { return _in_out_gubun; }
      set { _in_out_gubun = value; }
    }
    private string _hangmog_code = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hangmog_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_code
    {
      get { return _hangmog_code; }
      set { _hangmog_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
