//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FormSelectHospCodeResponse")]
  public partial class FormSelectHospCodeResponse : global::ProtoBuf.IExtensible
  {
    public FormSelectHospCodeResponse() {}
    
    private string _hosp_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hosp_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hosp_code
    {
      get { return _hosp_code; }
      set { _hosp_code = value; }
    }
    private string _hosp_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hosp_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hosp_name
    {
      get { return _hosp_name; }
      set { _hosp_name = value; }
    }
    private string _vpn_yn = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"vpn_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string vpn_yn
    {
      get { return _vpn_yn; }
      set { _vpn_yn = value; }
    }
    private string _cert_expired = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cert_expired", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cert_expired
    {
      get { return _cert_expired; }
      set { _cert_expired = value; }
    }
    private string _language = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"language", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string language
    {
      get { return _language; }
      set { _language = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
