//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHT0117Q00GrdCHT0118Info")]
  public partial class CHT0117Q00GrdCHT0118Info : global::ProtoBuf.IExtensible
  {
    public CHT0117Q00GrdCHT0118Info() {}
    
    private string _buwi = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"buwi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string buwi
    {
      get { return _buwi; }
      set { _buwi = value; }
    }
    private string _sub_buwi = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sub_buwi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sub_buwi
    {
      get { return _sub_buwi; }
      set { _sub_buwi = value; }
    }
    private string _sub_buwi_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sub_buwi_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sub_buwi_name
    {
      get { return _sub_buwi_name; }
      set { _sub_buwi_name = value; }
    }
    private string _cont_key = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cont_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cont_key
    {
      get { return _cont_key; }
      set { _cont_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
