//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS0103U10SetTabWonnaeDrgResponse")]
  public partial class OCS0103U10SetTabWonnaeDrgResponse : global::ProtoBuf.IExtensible
  {
    public OCS0103U10SetTabWonnaeDrgResponse() {}
    
    private readonly global::System.Collections.Generic.List<OCS0103U10SetTabWonnaeDrgInfo> _wonnae_drg_item = new global::System.Collections.Generic.List<OCS0103U10SetTabWonnaeDrgInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"wonnae_drg_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OCS0103U10SetTabWonnaeDrgInfo> wonnae_drg_item
    {
      get { return _wonnae_drg_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
