//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS0301Q09GrdOCS0303Response")]
  public partial class OCS0301Q09GrdOCS0303Response : global::ProtoBuf.IExtensible
  {
    public OCS0301Q09GrdOCS0303Response() {}
    
    private readonly global::System.Collections.Generic.List<OCS0301Q09GrdOCS0303Info> _grd_ocs_0303_item = new global::System.Collections.Generic.List<OCS0301Q09GrdOCS0303Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grd_ocs_0303_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OCS0301Q09GrdOCS0303Info> grd_ocs_0303_item
    {
      get { return _grd_ocs_0303_item; }
    }
  
    private readonly global::System.Collections.Generic.List<ComboListItemInfo> _combo_list_0307_item = new global::System.Collections.Generic.List<ComboListItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"combo_list_0307_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ComboListItemInfo> combo_list_0307_item
    {
      get { return _combo_list_0307_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
