//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS0301Q09TxtYaksokCodeDataValidatingRequest")]
  public partial class OCS0301Q09TxtYaksokCodeDataValidatingRequest : global::ProtoBuf.IExtensible
  {
    public OCS0301Q09TxtYaksokCodeDataValidatingRequest() {}
    
    private string _yaksok_open_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"yaksok_open_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string yaksok_open_id
    {
      get { return _yaksok_open_id; }
      set { _yaksok_open_id = value; }
    }
    private string _yaksok_code = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"yaksok_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string yaksok_code
    {
      get { return _yaksok_code; }
      set { _yaksok_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
