//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS0301U00LayQueryLayoutResponse")]
  public partial class OCS0301U00LayQueryLayoutResponse : global::ProtoBuf.IExtensible
  {
    public OCS0301U00LayQueryLayoutResponse() {}
    
    private readonly global::System.Collections.Generic.List<OCS0301U00LayoutInfo> _layout_info = new global::System.Collections.Generic.List<OCS0301U00LayoutInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"layout_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OCS0301U00LayoutInfo> layout_info
    {
      get { return _layout_info; }
    }
  
    private readonly global::System.Collections.Generic.List<OCS0301U00Membgrd307Info> _list_info = new global::System.Collections.Generic.List<OCS0301U00Membgrd307Info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OCS0301U00Membgrd307Info> list_info
    {
      get { return _list_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
