//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCSAPPROVEGrdPatientListResponse")]
  public partial class OCSAPPROVEGrdPatientListResponse : global::ProtoBuf.IExtensible
  {
    public OCSAPPROVEGrdPatientListResponse() {}
    
    private readonly global::System.Collections.Generic.List<OCSAPPROVEGrdPatientListInfo> _grd_patient_list_info = new global::System.Collections.Generic.List<OCSAPPROVEGrdPatientListInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grd_patient_list_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OCSAPPROVEGrdPatientListInfo> grd_patient_list_info
    {
      get { return _grd_patient_list_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
