package nta.med.app.vertx.ihis;

import nta.med.core.infrastructure.SpringBeanFactory;
import nta.med.core.infrastructure.socket.vertx.AbstractVerticle;
import nta.med.service.ihis.handler.nuri.*;
import nta.med.service.ihis.proto.NuriServiceProto;

public class NuriVerticle extends AbstractVerticle {

	public NuriVerticle() {
		super(NuriServiceProto.class, NuriServiceProto.getDescriptor());
	}

	@Override
	protected void doStart() throws Exception {
		registerHandler(NuriServiceProto.NuriNUR1016U00ValidationDuplicateCheckRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriValidationDuplicateCheckHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1016U00InsertNur1016Request.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1016U00InsertNur1016Handler.class));
		registerHandler(NuriServiceProto.NuriNUR1016U00UpdateNur1016Request.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1016U00UpdateNur1016Handler.class));
		registerHandler(NuriServiceProto.NuriNUR1016U00UpdateCancelStatusRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1016U00UpdateCancelStatusHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1016U00ManageAllergyListRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriManageAllergyListHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1016U00NurAlegyMappingRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1016U00NurAlegyMappingHandler.class));

		//[START] NUR7001U00 - Measure Physical condition
		registerHandler(NuriServiceProto.NuriNUR7001U00GetMaxSeqInNUR7001Request.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR7001U00GetMaxSeqInNUR7001Handler.class));
		registerHandler(NuriServiceProto.NuriNUR7001U00MeasurePhysicalConditionRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR7001U00MeasurePhysicalConditionHandler.class));
		registerHandler(NuriServiceProto.NuriNUR7001U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NuriNUR7001U00SaveLayoutHandler.class));

		//[END] NUR7001U00 - Measure Physical condition

		//[START] NUR1017U00 - Manage infection
		registerHandler(NuriServiceProto.NuriNUR1017U00ManageInfectionRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1017U00ManageInfectionHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1017U00GetYRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1017U00GetYHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1017U00GetCodeNameRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1017U00GetCodeNameHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1017U00InsertManageInfectionRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1017U00InsertManageInfectionHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1017U00UpdateManageInfectionRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1017U00UpdateManageInfectionHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1017U00DeleteManageInfectionRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1017U00DeleteManageInfectionHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1017U00InfeMappingRequest.class.getSimpleName(), SpringBeanFactory.beanFactory.getBean(NuriNUR1017U00InfeMappingHandler.class));
		registerHandler(NuriServiceProto.NUR1017U00GrdNUR1017Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1017U00GrdNUR1017Handler.class));
		registerHandler(NuriServiceProto.NUR1017U00GetComboListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1017U00GetComboListHandler.class));
		registerHandler(NuriServiceProto.NUR1017U00LayValidationDupchkRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1017U00LayValidationDupchkHandler.class));
		registerHandler(NuriServiceProto.NUR1017U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1017U00SaveLayoutHandler.class));
		//[END] NUR1017U00 - Manage infection

		//[START] NUR1016U00
		registerHandler(NuriServiceProto.NUR1016U00SelectNextValRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1016U00SelectNextValHandler.class));
		registerHandler(NuriServiceProto.NUR1016U00GetComboListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1016U00GetComboListHandler.class));
		registerHandler(NuriServiceProto.NUR1016U00GrdNUR1016Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1016U00GrdNUR1016Handler.class));
		registerHandler(NuriServiceProto.NUR1016U00PrNurAlergyMappingRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1016U00PrNurAlergyMappingHandler.class));
		registerHandler(NuriServiceProto.NuriNUR1016U00ValidationDuplicateCheckRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NuriValidationDuplicateCheckHandler.class));
		//[END] NUR1016U00

		//[START] NUR0101U01
		registerHandler(NuriServiceProto.NUR0101U01GrdDetailGridColumnChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U01GrdDetailGridColumnChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0101U01CheckDetailDBRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U01CheckDetailDBHandler.class));
		registerHandler(NuriServiceProto.NUR0101U01GrdMasterGridColumnChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U01GrdMasterGridColumnChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0101U01GrdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U01GrdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR0101U01GrdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U01GrdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR0101U01SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U01SaveLayoutHandler.class));
//		NUR0101U01SaveLayoutRequest
		//[END] NUR0101U01
		
		//[START] NURILIB
		registerHandler(NuriServiceProto.NURILIBChkBunhoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NURILIBChkBunhoHandler.class));
		registerHandler(NuriServiceProto.NURILIBChkGetWonyoiYnRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NURILIBChkGetWonyoiYnHandler.class));
		registerHandler(NuriServiceProto.NURILIBChkSimsaMagamINP1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NURILIBChkSimsaMagamINP1001Handler.class));
		registerHandler(NuriServiceProto.NURILIBGetBuseoNameBAS0260Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NURILIBGetBuseoNameBAS0260Handler.class));
		registerHandler(NuriServiceProto.NURILIBGetCodeNameBAS0102Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NURILIBGetCodeNameBAS0102Handler.class));
		registerHandler(NuriServiceProto.NURILIBGetDisGubunNameBAS0281Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NURILIBGetDisGubunNameBAS0281Handler.class));
		registerHandler(NuriServiceProto.NURILIBGetSuNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NURILIBGetSuNameHandler.class));
		registerHandler(NuriServiceProto.NURILIBIsJaewonRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NURILIBIsJaewonHandler.class));
		//[END] NURILIB
		
		registerHandler(NuriServiceProto.NUR2017Q00grdNUR2017Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2017Q00grdNUR2017Handler.class));
		registerHandler(NuriServiceProto.NUR2017Q00xEditGridCell30Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2017Q00xEditGridCell30Handler.class));
		registerHandler(NuriServiceProto.NUR2017Q00grdNUR2017QueryEndRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2017Q00grdNUR2017QueryEndHandler.class));
		
		registerHandler(NuriServiceProto.NUR0811U00CboRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0811U00CboHandler.class));
		registerHandler(NuriServiceProto.NUR0811U00GrdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0811U00GrdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR0811U00GrdColChangeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0811U00GrdColChangeHandler.class));
		registerHandler(NuriServiceProto.NUR0811U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0811U00SaveLayoutHandler.class));
		
		registerHandler(NuriServiceProto.NUR2004U01fwBedNoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01fwBedNoHandler.class));
		registerHandler(NuriServiceProto.NUR2004U01grdInp2004Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01grdInp2004Handler.class));
		registerHandler(NuriServiceProto.NUR2004U01PRBASBAS0250REFRESHRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01PRBASBAS0250REFRESHHandler.class));
		registerHandler(NuriServiceProto.NUR2004U01ConfirmTransRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01ConfirmTransHandler.class));
		registerHandler(NuriServiceProto.NUR2004U01GetConfirmDataRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01GetConfirmDataHandler.class));
		registerHandler(NuriServiceProto.NUR2004U01PRINPUPDATEJENGWARequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01PRINPUPDATEJENGWAHandler.class));
		registerHandler(NuriServiceProto.NUR2004U01PRNURCHANGEGWAHODONGRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01PRNURCHANGEGWAHODONGHandler.class));
		registerHandler(NuriServiceProto.NUR2004U01GetSubConfirmData1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01GetSubConfirmData1Handler.class));
		registerHandler(NuriServiceProto.NUR2004U01GetSubConfirmData2Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01GetSubConfirmData2Handler.class));
		registerHandler(NuriServiceProto.NUR2004U01GetSubConfirmData3Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01GetSubConfirmData3Handler.class));
		registerHandler(NuriServiceProto.NUR2004U01layCommonRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01layCommonHandler.class));
		registerHandler(NuriServiceProto.NUR2004U01GetSubConfirmData4Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U01GetSubConfirmData4Handler.class));
		registerHandler(NuriServiceProto.NUR0812U00CboRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0812U00CboHandler.class));
		registerHandler(NuriServiceProto.NUR0812U00FwkGubunRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0812U00FwkGubunHandler.class));
		registerHandler(NuriServiceProto.NUR0812U00GrdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0812U00GrdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR0812U00GrdDetailColChangeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0812U00GrdDetailColChangeHandler.class));
		registerHandler(NuriServiceProto.NUR0812U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0812U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR1123U00grdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1123U00grdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR1123U00grdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1123U00grdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR1123U00grdMasterCheckRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1123U00grdMasterCheckHandler.class));
		registerHandler(NuriServiceProto.NUR1123U00grdDetailCheckRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1123U00grdDetailCheckHandler.class));
		
		registerHandler(NuriServiceProto.NUR0101U00grdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U00grdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR0101U00grdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U00grdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR0101U00layComboItemsRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U00layComboItemsHandler.class));
		registerHandler(NuriServiceProto.NUR0101U00grdMasterGridColumnChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U00grdMasterGridColumnChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0101U00grdDetailGridColumnChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U00grdDetailGridColumnChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0101U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0101U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR1123U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1123U00SaveLayoutHandler.class));
		
		registerHandler(NuriServiceProto.NUR6011U01grdImageRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01grdImageHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01grdNur6011Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01grdNur6011Handler.class));
		registerHandler(NuriServiceProto.NUR6011U01grdNur6012Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01grdNur6012Handler.class));
		registerHandler(NuriServiceProto.NUR6011U01grdNur6012CopyRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01grdNur6012CopyHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01layCalendarRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01layCalendarHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01layImageRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01layImageHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01LoadFtpOptionRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01LoadFtpOptionHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01BuwiNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01BuwiNameHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01IsJaewonRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01IsJaewonHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01GetNur6005Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01GetNur6005Handler.class));
		registerHandler(NuriServiceProto.NUR6011U01GetNurseInfoLifeSelfGradeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01GetNurseInfoLifeSelfGradeHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01GetNurseInfoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01GetNurseInfoHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01GetGumsaRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01GetGumsaHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01OnPopMenuClickRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01OnPopMenuClickHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01fwkAssessorHoDong1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01fwkAssessorHoDong1Handler.class));
		registerHandler(NuriServiceProto.NUR6011U01UserNmByBuseoNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01UserNmByBuseoNameHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01LoadUserNmRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01LoadUserNmHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01layComboSetRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01layComboSetHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01PrintSetgrdPrintRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01PrintSetgrdPrintHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01PrintSetlayBuwiRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01PrintSetlayBuwiHandler.class));
		registerHandler(NuriServiceProto.NUR6011U01PrintSetlayImageRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6011U01PrintSetlayImageHandler.class));
		
		registerHandler(NuriServiceProto.NUR2004U00layCurrentBedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layCurrentBedHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layHocodeBednoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layHocodeBednoHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layMaxBedNoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layMaxBedNoHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layHoSexRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layHoSexHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00cboFromToHoGradeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00cboFromToHoGradeHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00cboToKaikeiRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00cboToKaikeiHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00fbxToGwaRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00fbxToGwaHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00fbxToDoctorRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00fbxToDoctorHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00fbxToHodongRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00fbxToHodongHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00fbxToHoCodeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00fbxToHoCodeHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layValidCheckGwaRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layValidCheckGwaHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layValidCheckDoctorRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layValidCheckDoctorHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layValidCheckHodongRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layValidCheckHodongHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layValidCheckHocodeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layValidCheckHocodeHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00GetInitJunipRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00GetInitJunipHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00CancelCheckRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CancelCheckHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00getHogradeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00getHogradeHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00CheckAfterHogradeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CheckAfterHogradeHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00CheckBeforeUpdateRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CheckBeforeUpdateHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00getTransCntRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00getTransCntHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00getOldTransCntRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00getOldTransCntHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00CancelUpdateRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CancelUpdateHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00ProcessUpdateRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00ProcessUpdateHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00ProcessInsertRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00ProcessInsertHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00cboDungsyochiRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00cboDungsyochiHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00fwkWriterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00fwkWriterHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00grdNUR1020Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00grdNUR1020Handler.class));
		registerHandler(NuriServiceProto.NUR1020U00grdNUR1022INRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00grdNUR1022INHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00grdNUR1122Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00grdNUR1122Handler.class));
		registerHandler(NuriServiceProto.NUR1020U00grdPalistRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00grdPalistHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00layHangmogRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00layHangmogHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00layNUR7002Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00layNUR7002Handler.class));
		registerHandler(NuriServiceProto.NUR1020U00layNURListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00layNURListHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00laySiksaRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00laySiksaHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00layWriterBARequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00layWriterBAHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00GrdAndComboRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00GrdAndComboHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00GrdWatchTemplateRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00GrdWatchTemplateHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00LayComboRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00LayComboHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00QueryRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00QueryHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00GetFkinp1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00GetFkinp1001Handler.class));
		registerHandler(NuriServiceProto.NUR1020U00InputLockRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00InputLockHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00SelectHodong1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00SelectHodong1Handler.class));
		registerHandler(NuriServiceProto.NUR1020U00btnTimeApplyClickRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00btnTimeApplyClickHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00btnPreChuchiClickRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00btnPreChuchiClickHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00SetCycleOrderGroupRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00SetCycleOrderGroupHandler.class));
		registerHandler(NuriServiceProto.NUR1020U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00GetConfirmDataUpdateRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00GetConfirmDataUpdateHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00ConfirmTransRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00ConfirmTransHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00ConfirmTransCancelRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00ConfirmTransCancelHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layCurrentBedHoTotalBedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layCurrentBedHoTotalBedHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00layCurrentBedTransRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layCurrentBedTransHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00dtpJukyongRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00dtpJukyongHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00prBas0250Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00prBas0250Handler.class));
		registerHandler(NuriServiceProto.NUR2004U00prMakeIpwonRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00prMakeIpwonHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00prUpdateJengwaRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00prUpdateJengwaHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00prNurChangeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00prNurChangeHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00getBedNoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00getBedNoHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00CheckPreInsert1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CheckPreInsert1Handler.class));
		registerHandler(NuriServiceProto.NUR2004U00CheckPreInsert2Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CheckPreInsert2Handler.class));
		registerHandler(NuriServiceProto.NUR2004U00CheckPreInsert3Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CheckPreInsert3Handler.class));
		registerHandler(NuriServiceProto.NUR2004U00CheckPreInsert4Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CheckPreInsert4Handler.class));
		registerHandler(NuriServiceProto.NUR2004U00CheckPreInsert5Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00CheckPreInsert5Handler.class));
		registerHandler(NuriServiceProto.NUR2004U00GetConfirmDataSelectRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00GetConfirmDataSelectHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00GetConfirmDataCheck1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00GetConfirmDataCheck1Handler.class));
		registerHandler(NuriServiceProto.NUR2004U00GetConfirmDataLoadSimsaYnRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00GetConfirmDataLoadSimsaYnHandler.class));
		registerHandler(NuriServiceProto.NUR2004U00GetConfirmDataCheck2Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00GetConfirmDataCheck2Handler.class));
		registerHandler(NuriServiceProto.NUR2004U00layCommonRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2004U00layCommonHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0110Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0110Handler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0111Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0111Handler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0112Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0112Handler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0113Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0113Handler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0114Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0114Handler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0115Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0115Handler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR01152Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR01152Handler.class));
		registerHandler(NuriServiceProto.NUR0110U00GetJisiOrderGubunRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GetJisiOrderGubunHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNur0110ColChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNur0110ColChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNur0111ColChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNur0111ColChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNur0112ColChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNur0112ColChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNur0113ColChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNur0113ColChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNur0114ColChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNur0114ColChangedHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GetJaeryoYNRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GetJaeryoYNHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GetOrdDanuiRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GetOrdDanuiHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GetOrdDanuiNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GetOrdDanuiNameHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GetInsertOrderGubunRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GetInsertOrderGubunHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GetCanInsertSlipCodeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GetCanInsertSlipCodeHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00CommandRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00CommandHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00CreateComboRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00CreateComboHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00SetInputControlRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00SetInputControlHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00SetFindWorkerRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00SetFindWorkerHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0115FindClickRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0115FindClickHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0115Case1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0115Case1Handler.class));
		registerHandler(NuriServiceProto.NUR0110U00GrdNUR0115ColChangeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00GrdNUR0115ColChangeHandler.class));
		registerHandler(NuriServiceProto.NUR0110U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0110U00SaveLayoutHandler.class));
		
		registerHandler(NuriServiceProto.NUR1010Q00layHosilListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00layHosilListHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00layPatientRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00layPatientHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00layBedListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00layBedListHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00layConfirmDataRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00layConfirmDataHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00layTimeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00layTimeHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00grdGwaCountRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00grdGwaCountHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00AdmMsgRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00AdmMsgHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00SelectDokboRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00SelectDokboHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00SelectMancntRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00SelectMancntHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00SelectHosexRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00SelectHosexHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00fnLoadIlsuRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00fnLoadIlsuHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00SelectCountRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00SelectCountHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00UpdateSetBedStatusRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00UpdateSetBedStatusHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00CheckNurseIDRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00CheckNurseIDHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00MoveHosilCheck1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00MoveHosilCheck1Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00ChangeMoveHosilCheck2Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00ChangeMoveHosilCheck2Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00MoveHosilCheck3Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00MoveHosilCheck3Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00MoveHosilCheck4Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00MoveHosilCheck4Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00MoveHosilSelect1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00MoveHosilSelect1Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00ChangeMoveHosilSelect2Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00ChangeMoveHosilSelect2Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00MoveHosilInsert1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00MoveHosilInsert1Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00ChangeHosilCheck3Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00ChangeHosilCheck3Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00ChangeHosilCheck4Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00ChangeHosilCheck4Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00ChangeHosilSelect1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00ChangeHosilSelect1Handler.class));
		registerHandler(NuriServiceProto.NUR1010Q00ChangeHosilInsertRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00ChangeHosilInsertHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00layCommonRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00layCommonHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00GetConfirmDataUpdateRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00GetConfirmDataUpdateHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00ConfirmTransRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00ConfirmTransHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00ConfirmTransCancelRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00ConfirmTransCancelHandler.class));
		registerHandler(NuriServiceProto.NUR1010Q00prNurChangeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010Q00prNurChangeHandler.class));
		registerHandler(NuriServiceProto.NUR2017U01grdNUR2017Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2017U01grdNUR2017Handler.class));
		registerHandler(NuriServiceProto.NUR2017U01grdPalistRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2017U01grdPalistHandler.class));
		registerHandler(NuriServiceProto.NUR2017U01OCS0132CodeNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2017U01OCS0132CodeNameHandler.class));
		registerHandler(NuriServiceProto.NUR2017U01layCommonRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2017U01layCommonHandler.class));
		registerHandler(NuriServiceProto.NUR2017U01SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR2017U01SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR0801U00GrdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0801U00GrdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR0801U00GrdMasterColChangeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0801U00GrdMasterColChangeHandler.class));
		registerHandler(NuriServiceProto.NUR0801U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0801U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR0801U00XEditGridRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0801U00XEditGridHandler.class));
		
		registerHandler(NuriServiceProto.NUR1001R09layHodongPrintRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001R09layHodongPrintHandler.class));
		registerHandler(NuriServiceProto.NUR1001R09cboWingGubunRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001R09cboWingGubunHandler.class));
		registerHandler(NuriServiceProto.NUR1001R09grdINP1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001R09grdINP1001Handler.class));
		registerHandler(NuriServiceProto.NUR8003Q00grdWritedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003Q00grdWritedHandler.class));
		registerHandler(NuriServiceProto.NUR8003Q00grdNur8003Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003Q00grdNur8003Handler.class));
		registerHandler(NuriServiceProto.NUR8003Q00cboBuseoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003Q00cboBuseoHandler.class));
		registerHandler(NuriServiceProto.NUR1010U00grdNur1010Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010U00grdNur1010Handler.class));
		registerHandler(NuriServiceProto.NUR1010U00fwkNurseRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010U00fwkNurseHandler.class));
		registerHandler(NuriServiceProto.NUR1010U00grdNurCheckRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010U00grdNurCheckHandler.class));
		registerHandler(NuriServiceProto.NUR1010U00LoadUserNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010U00LoadUserNameHandler.class));
		registerHandler(NuriServiceProto.NUR1010U00DamdangNurseRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010U00DamdangNurseHandler.class));
		registerHandler(NuriServiceProto.NUR1010U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1010U00SaveLayoutHandler.class));
		
		registerHandler(NuriServiceProto.NUR1001R07grdInp1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001R07grdInp1001Handler.class));
		registerHandler(NuriServiceProto.NUR1001R07grdInp2004Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001R07grdInp2004Handler.class));
		registerHandler(NuriServiceProto.NUR1035U00grdNUR1035Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1035U00grdNUR1035Handler.class));
		registerHandler(NuriServiceProto.NUR1035U00grdNUR1036Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1035U00grdNUR1036Handler.class));
		registerHandler(NuriServiceProto.NUR1035U00grdPalistRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1035U00grdPalistHandler.class));
		registerHandler(NuriServiceProto.NUR1035U00xEditGridCellLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1035U00xEditGridCellLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR1035U00pknur1035Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1035U00pknur1035Handler.class));
		registerHandler(NuriServiceProto.NUR1035U00cmdTextRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1035U00cmdTextHandler.class));
		registerHandler(NuriServiceProto.NUR1035U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1035U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR0401U01GrdNur0102Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01GrdNur0102Handler.class));
		registerHandler(NuriServiceProto.NUR0401U01GrdNur0401Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01GrdNur0401Handler.class));
		registerHandler(NuriServiceProto.NUR0401U01GrdNur0403Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01GrdNur0403Handler.class));
		registerHandler(NuriServiceProto.NUR0401U01GrdNur0404Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01GrdNur0404Handler.class));
		registerHandler(NuriServiceProto.NUR0401U01LayNurPlanBunryuRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01LayNurPlanBunryuHandler.class));
		registerHandler(NuriServiceProto.NUR0401U01LayTabColorRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01LayTabColorHandler.class));
		registerHandler(NuriServiceProto.NUR0401U01GetCodeNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01GetCodeNameHandler.class));
		registerHandler(NuriServiceProto.NUR0401U01IsExistDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01IsExistDetailHandler.class));
		registerHandler(NuriServiceProto.NUR0401U01IsUsedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01IsUsedHandler.class));
		registerHandler(NuriServiceProto.NUR0401U01SelectNewCode0401Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01SelectNewCode0401Handler.class));
		registerHandler(NuriServiceProto.NUR0401U01SelectSeq0403Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01SelectSeq0403Handler.class));
		registerHandler(NuriServiceProto.NUR0401U01SelectNewCode0404Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01SelectNewCode0404Handler.class));
		registerHandler(NuriServiceProto.NUR0401U01BtnListDeleteRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01BtnListDeleteHandler.class));
		registerHandler(NuriServiceProto.NUR0401U01SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0401U01SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR0802U00fwkGubunRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0802U00fwkGubunHandler.class));
		registerHandler(NuriServiceProto.NUR0802U00grdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0802U00grdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR0802U00grdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0802U00grdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR0802U00xEditGridCelRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0802U00xEditGridCelHandler.class));
		registerHandler(NuriServiceProto.NUR0802U00cmdTextRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0802U00cmdTextHandler.class));
		registerHandler(NuriServiceProto.NUR0802U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0802U00SaveLayoutHandler.class));
		
		registerHandler(NuriServiceProto.NUR1014U00grdNur1014Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1014U00grdNur1014Handler.class));
		registerHandler(NuriServiceProto.NUR1014U00CheckOrderRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1014U00CheckOrderHandler.class));
		registerHandler(NuriServiceProto.NUR1014U00ValidationCheckRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1014U00ValidationCheckHandler.class));
		registerHandler(NuriServiceProto.NUR1014U00xEditGridCell14Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1014U00xEditGridCell14Handler.class));
		registerHandler(NuriServiceProto.NUR1014U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1014U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR4001U00FwkJinRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4001U00FwkJinHandler.class));
		registerHandler(NuriServiceProto.NUR4001U00GrdNUR4001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4001U00GrdNUR4001Handler.class));
		registerHandler(NuriServiceProto.NUR4001U00LayNewNUR4001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4001U00LayNewNUR4001Handler.class));
		registerHandler(NuriServiceProto.NUR4001U00LayComboRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4001U00LayComboHandler.class));
		registerHandler(NuriServiceProto.NUR4001U00IsExistNUR4005Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4001U00IsExistNUR4005Handler.class));
		registerHandler(NuriServiceProto.NUR4001U00SelectPatientRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4001U00SelectPatientHandler.class));
		registerHandler(NuriServiceProto.NUR4001U00LayPlanQueryStartRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4001U00LayPlanQueryStartHandler.class));
		registerHandler(NuriServiceProto.NUR4001U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4001U00SaveLayoutHandler.class));
		
		registerHandler(NuriServiceProto.NUR1001U00FwkFindRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00FwkFindHandler.class));
		registerHandler(NuriServiceProto.NUR1001U00GrdINP1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00GrdINP1001Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00GrdINP1004Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00GrdINP1004Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00GrdNUR1002Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00GrdNUR1002Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00GrdNUR1016Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00GrdNUR1016Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00GrdNUR1017Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00GrdNUR1017Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00GrdOUT0106Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00GrdOUT0106Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00LayFkinp1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00LayFkinp1001Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00LayINP1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00LayINP1001Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00LayNUR1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00LayNUR1001Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00GrdNUR1029Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00GrdNUR1029Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00LayComboSetRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00LayComboSetHandler.class));
		registerHandler(NuriServiceProto.NUR1001U00LayReserInfoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00LayReserInfoHandler.class));
		registerHandler(NuriServiceProto.NUR1001U00BasicQuery1Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00BasicQuery1Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00BasicQuery2Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00BasicQuery2Handler.class));
		registerHandler(NuriServiceProto.NUR1001U00CboScreenOpenRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00CboScreenOpenHandler.class));
		registerHandler(NuriServiceProto.NUR1001U00FindBoxClickRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00FindBoxClickHandler.class));
		registerHandler(NuriServiceProto.NUR1001U00DtpBirthValidateRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00DtpBirthValidateHandler.class));
		registerHandler(NuriServiceProto.NUR1001U00GrdNUR1029FindClickRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00GrdNUR1029FindClickHandler.class));
		registerHandler(NuriServiceProto.NUR1001U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1001U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00fwkFindRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00fwkFindHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00layComboSetRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00layComboSetHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00layBojoListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00layBojoListHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00layWorkTimeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00layWorkTimeHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00layNur4001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00layNur4001Handler.class));
		registerHandler(NuriServiceProto.NUR9001U00layComboNur4001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00layComboNur4001Handler.class));
		registerHandler(NuriServiceProto.NUR9001U00fwkNurseRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00fwkNurseHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00grdPalistRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00grdPalistHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00grdNur9001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00grdNur9001Handler.class));
		registerHandler(NuriServiceProto.NUR9001U00fkInp1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00fkInp1001Handler.class));
		registerHandler(NuriServiceProto.NUR9001U00Nur9001dataCheckRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00Nur9001dataCheckHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00lblBojoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00lblBojoHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00fnPlanEndRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00fnPlanEndHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00fnLoadUserRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00fnLoadUserHandler.class));
		registerHandler(NuriServiceProto.NUR9001U00getAdminUserRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9001U00getAdminUserHandler.class));
		registerHandler(NuriServiceProto.NUR1091U00grdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1091U00grdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR1091U00grdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1091U00grdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR1091U00grdMasterGridColumnChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1091U00grdMasterGridColumnChangedHandler.class));
		registerHandler(NuriServiceProto.NUR1091U00grdDetailGridColumnChangedRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1091U00grdDetailGridColumnChangedHandler.class));
		registerHandler(NuriServiceProto.NUR1091U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1091U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layConmentRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layConmentHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00ScreenOpenRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00ScreenOpenHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00grdPalistRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00grdPalistHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layFlagQueryRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layFlagQueryHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layGraphRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layGraphHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layInOutTotalRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layInOutTotalHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layIORequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layIOHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layIpwonInfoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layIpwonInfoHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layNUR1122ListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layNUR1122ListHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layNUR7002Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layNUR7002Handler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layNutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layNutHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layQueryRemarkRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layQueryRemarkHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00laySiksaNoteRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00laySiksaNoteHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00laySusulInfoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00laySusulInfoHandler.class));
		registerHandler(NuriServiceProto.NUR1020Q00layNUR1122Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1020Q00layNUR1122Handler.class));
		registerHandler(NuriServiceProto.NUR8003R02cboHoDongRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003R02cboHoDongHandler.class));
		registerHandler(NuriServiceProto.NUR8003R02grdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003R02grdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR8003R02grdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003R02grdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR8003R02grdPayloadDataRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003R02grdPayloadDataHandler.class));
		registerHandler(NuriServiceProto.NUR8003R02cboNeedHTypeRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003R02cboNeedHTypeHandler.class));
		registerHandler(NuriServiceProto.NUR1093U00grdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1093U00grdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR1093U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1093U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR1094U00Cell34Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00Cell34Handler.class));
		registerHandler(NuriServiceProto.NUR1094U00GetFkInp1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00GetFkInp1001Handler.class));
		registerHandler(NuriServiceProto.NUR1094U00GetLevelRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00GetLevelHandler.class));
		registerHandler(NuriServiceProto.NUR1094U00GetLevelNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00GetLevelNameHandler.class));
		registerHandler(NuriServiceProto.NUR1094U00GetUserNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00GetUserNameHandler.class));
		registerHandler(NuriServiceProto.NUR1094U00GrdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00GrdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR1094U00GrdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00GrdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR1094U00GrdPalistRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00GrdPalistHandler.class));
		registerHandler(NuriServiceProto.NUR1094U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1094U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR0803U01grdNUR0803Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0803U01grdNUR0803Handler.class));
		registerHandler(NuriServiceProto.NUR0803U01grdNUR0804Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0803U01grdNUR0804Handler.class));
		registerHandler(NuriServiceProto.NUR0803U01grdNUR0805Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0803U01grdNUR0805Handler.class));
		registerHandler(NuriServiceProto.NUR0803U01grdMasterRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0803U01grdMasterHandler.class));
		registerHandler(NuriServiceProto.NUR0803U01grdDetailRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0803U01grdDetailHandler.class));
		registerHandler(NuriServiceProto.NUR0803U01SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR0803U01SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdNURCntRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdNURCntHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdWatchListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdWatchListHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdCommentRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdCommentHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdGuhoGubunRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdGuhoGubunHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdWoiRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdWoiHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdIpToiRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdIpToiHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdTransRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdTransHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdSusulRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdSusulHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdGwaRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdGwaHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00grdBedSoreRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00grdBedSoreHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00fwkNurseRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00fwkNurseHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00layConfirmYnRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layConfirmYnHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00layGamyumCntRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layGamyumCntHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00layNur5020Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layNur5020Handler.class));
		registerHandler(NuriServiceProto.NUR5020U00layNurCntRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layNurCntHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00layPatientInfoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layPatientInfoHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00layPatientInfoInRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layPatientInfoInHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00layPatientInfoOutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layPatientInfoOutHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00layStairCntRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layStairCntHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00layTotalCntRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00layTotalCntHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00SaveNur5200Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00SaveNur5200Handler.class));
		registerHandler(NuriServiceProto.NUR5020U00XEditGridCellRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00XEditGridCellHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00fbxNurseDataValidatingRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00fbxNurseDataValidatingHandler.class));
		registerHandler(NuriServiceProto.NUR5020U00PRNURNUR5200SUBDELETERequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR5020U00PRNURNUR5200SUBDELETEHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03CboHoDongRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03CboHoDongHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03GrdARequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03GrdAHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03GrdPalistRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03GrdPalistHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03LayNurPointsRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03LayNurPointsHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03GetKaikeiHodongRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03GetKaikeiHodongHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03DeleteTodayAllRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03DeleteTodayAllHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03SetFindWorkerRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03SetFindWorkerHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03CopyDataRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03CopyDataHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03QueryFormGrdBPRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03QueryFormGrdBPHandler.class));
		registerHandler(NuriServiceProto.NUR8003U03QueryFormGrdSyochiRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8003U03QueryFormGrdSyochiHandler.class));
		registerHandler(NuriServiceProto.NUR8050U00cboGubunRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8050U00cboGubunHandler.class));
		registerHandler(NuriServiceProto.NUR8050U00grdNur8050AllRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8050U00grdNur8050AllHandler.class));
		registerHandler(NuriServiceProto.NUR8050U00grdNur8050HisRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8050U00grdNur8050HisHandler.class));
		registerHandler(NuriServiceProto.NUR8050U00fwkNurseRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8050U00fwkNurseHandler.class));
		registerHandler(NuriServiceProto.NUR8050U00NurseNameRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8050U00NurseNameHandler.class));
		registerHandler(NuriServiceProto.NUR8050U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8050U00SaveLayoutHandler.class));		
		registerHandler(NuriServiceProto.NUR9999R11SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9999R11SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR9999R11grdNUR9999Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9999R11grdNUR9999Handler.class));
		registerHandler(NuriServiceProto.NUR9999R11layPaInfoRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9999R11layPaInfoHandler.class));
		registerHandler(NuriServiceProto.NUR9999R11comboBoxRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9999R11comboBoxHandler.class));
		registerHandler(NuriServiceProto.NUR9999R11sqlCmdRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9999R11sqlCmdHandler.class));
		registerHandler(NuriServiceProto.NUR9999R11cboPkInp1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR9999R11cboPkInp1001Handler.class));
		registerHandler(NuriServiceProto.NUR6005U00grdNUR6005Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6005U00grdNUR6005Handler.class));
		registerHandler(NuriServiceProto.NUR6005U00layComboSetRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6005U00layComboSetHandler.class));
		registerHandler(NuriServiceProto.NUR6005U00layFkinp1001Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6005U00layFkinp1001Handler.class));
		registerHandler(NuriServiceProto.NUR6005U00layValidationDupchkRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6005U00layValidationDupchkHandler.class));
		registerHandler(NuriServiceProto.NUR6005U00SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR6005U00SaveLayoutHandler.class));
		registerHandler(NuriServiceProto.NUR8050U00cboGrdNur8050HisRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR8050U00cboGrdNur8050HisHandler.class));
		registerHandler(NuriServiceProto.NUR1091Q00layRootListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1091Q00layRootListHandler.class));
		registerHandler(NuriServiceProto.NUR1091Q00layDownListRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR1091Q00layDownListHandler.class));
		registerHandler(NuriServiceProto.NUR4005U01FwkNurseRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4005U01FwkNurseHandler.class));
		registerHandler(NuriServiceProto.NUR4005U01GrdNUR4005Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4005U01GrdNUR4005Handler.class));
		registerHandler(NuriServiceProto.NUR4005U01XCell2Request.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4005U01XCell2Handler.class));
		registerHandler(NuriServiceProto.NUR4005U01SaveLayoutRequest.class.getSimpleName(),SpringBeanFactory.beanFactory.getBean(NUR4005U01SaveLayoutHandler.class));
	}

	@Override
	protected void doStop() throws Exception {

	}
}
