//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
// Note: requires additional types generated from: mixed_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ADM102UGrdListItemInfo")]
  public partial class ADM102UGrdListItemInfo : global::ProtoBuf.IExtensible
  {
    public ADM102UGrdListItemInfo() {}
    
    private string _pgm_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pgm_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pgm_id
    {
      get { return _pgm_id; }
      set { _pgm_id = value; }
    }
    private string _pgm_nm = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pgm_nm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pgm_nm
    {
      get { return _pgm_nm; }
      set { _pgm_nm = value; }
    }
    private string _pgm_tp = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pgm_tp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pgm_tp
    {
      get { return _pgm_tp; }
      set { _pgm_tp = value; }
    }
    private string _sys_id = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sys_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sys_id
    {
      get { return _sys_id; }
      set { _sys_id = value; }
    }
    private string _prod_id = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"prod_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prod_id
    {
      get { return _prod_id; }
      set { _prod_id = value; }
    }
    private string _srvc_id = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"srvc_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string srvc_id
    {
      get { return _srvc_id; }
      set { _srvc_id = value; }
    }
    private string _pgm_ent_grad = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pgm_ent_grad", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pgm_ent_grad
    {
      get { return _pgm_ent_grad; }
      set { _pgm_ent_grad = value; }
    }
    private string _pgm_upd_grad = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pgm_upd_grad", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pgm_upd_grad
    {
      get { return _pgm_upd_grad; }
      set { _pgm_upd_grad = value; }
    }
    private string _pgm_scrt = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pgm_scrt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pgm_scrt
    {
      get { return _pgm_scrt; }
      set { _pgm_scrt = value; }
    }
    private string _pgm_dup_yn = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pgm_dup_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pgm_dup_yn
    {
      get { return _pgm_dup_yn; }
      set { _pgm_dup_yn = value; }
    }
    private string _end_yn = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"end_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string end_yn
    {
      get { return _end_yn; }
      set { _end_yn = value; }
    }
    private string _pgm_acs_yn = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pgm_acs_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pgm_acs_yn
    {
      get { return _pgm_acs_yn; }
      set { _pgm_acs_yn = value; }
    }
    private string _mang_memb = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mang_memb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mang_memb
    {
      get { return _mang_memb; }
      set { _mang_memb = value; }
    }
    private string _asm_name = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"asm_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string asm_name
    {
      get { return _asm_name; }
      set { _asm_name = value; }
    }
    private string _row_state = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"row_state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string row_state
    {
      get { return _row_state; }
      set { _row_state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
