//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHIS.OCSA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IHIS.OCSA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確 認.
        /// </summary>
        internal static string Caption_1 {
            get {
                return ResourceManager.GetString("Caption_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        internal static string Caption_2 {
            get {
                return ResourceManager.GetString("Caption_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コードデータを入力するためには、まずコード類型データをご入力ください。.
        /// </summary>
        internal static string MSG_1 {
            get {
                return ResourceManager.GetString("MSG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失敗しました. 確認願います..
        /// </summary>
        internal static string MSG_10 {
            get {
                return ResourceManager.GetString("MSG_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コード区分名を入力してください.
        /// </summary>
        internal static string MSG_11_IPNAME {
            get {
                return ResourceManager.GetString("MSG_11_IPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コード区分を入力してください.
        /// </summary>
        internal static string MSG_12_IPCODE {
            get {
                return ResourceManager.GetString("MSG_12_IPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コード類型[{0}]　　削除するためには、該当コード類型のコード情報を先に削除してください。.
        /// </summary>
        internal static string MSG_2 {
            get {
                return ResourceManager.GetString("MSG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コードタイプの入力値が正しくありません。 ご確認ください。.
        /// </summary>
        internal static string MSG_3 {
            get {
                return ResourceManager.GetString("MSG_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既存の登録データ[{0}]が　存在します。確認してください. 確認してください..
        /// </summary>
        internal static string MSG_4 {
            get {
                return ResourceManager.GetString("MSG_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コードデータを入力しようとすればコード類型データを先に入力をしなければならないです..
        /// </summary>
        internal static string MSG_5 {
            get {
                return ResourceManager.GetString("MSG_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既存の登録データ[{0}]が　存在します. 確認してください..
        /// </summary>
        internal static string MSG_6 {
            get {
                return ResourceManager.GetString("MSG_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常に保存になりました..
        /// </summary>
        internal static string MSG_7 {
            get {
                return ResourceManager.GetString("MSG_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失敗しました. 確認願います..
        /// </summary>
        internal static string MSG_8 {
            get {
                return ResourceManager.GetString("MSG_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存が完了しました。.
        /// </summary>
        internal static string MSG_9 {
            get {
                return ResourceManager.GetString("MSG_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失敗しました. 確認願います..
        /// </summary>
        internal static string MSG_SAVE_ERROR {
            get {
                return ResourceManager.GetString("MSG_SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存が完了しました。.
        /// </summary>
        internal static string MSG_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS", resourceCulture);
            }
        }
    }
}
