package nta.med.core.glossary;

public enum CommonEnum {
	DOT("."),
	COMMA(","),
	UNDERSCORE("_"),
	VERTICALBAR("|"),
	QUESTION_SENT("SENT"),
	QUESTION_RECEIVED("RECEIVED"),
	QUESTION_DEPARMENT("DEPARMENT"),
	QUESTION_STATUS_NEW("1"),
	QUESTION_STATUS_ANSWERED("2"),
	QUESTION_STATUS_REQUEST_DOCTOR_REPLIED("3"),
	S("S"),
	O("O"),
	SETORDER("SetOrder"),
	DOCTOR("Doctor"),
	OCS1003("OCS1003"),
	OCS2003("OCS2003"),
	MINUS_SIGN("-"),
	ICON1("オーダ無し"),
	ICON2("未処理オーダ有り"),
	ICON3("オーダ全部処理済み"),
	ICON1_MULTI_LANGUAGE("NO_ORDER"),
	ICON2_MULTI_LANGUAGE("UNPROCESSED"),
	ICON3_MULTI_LANGUAGE("PROCESSED"),
	SYSTEM_ID_NURO("NURO"),
	SYSTEM_ID_NURI("NURI"),
	SYSTEM_ID_TSTS("TSTS"),
	PERCENTAGE("%"),
	JUNDAL_TABLE_INJ("INJ"),
	JUNDAL_TABLE_PFE("PFE"),
	JUNDAL_TABLE_TST("TST"),
	JUNDAL_TABLE_CPL("CPL"),
	EMAIL_TEMPLATE_INFORM_CASE_VPN("DEMO_ACCOUNT_INFORMATION"),
	EMAIL_TEMPLATE_INFORM_CASE_NO_VPN("DEMO_ACCOUNT_INFORMATION_NO_VPN"),
	HOSP_CODE_ENCRYP("hosp_code_encryp"),
	TAB_INVOICE_PAY("02"),
	TAB_INVOICE_UNPAY("01"),
	TAB_INVOICE_CANCEL("03"),
	TAB_INVOICE_UNCOMPLETED("04"),
	BEFORE("Before")
	;

	private String value;

	CommonEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}
