//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ORCALibGetClaimPatientInfo")]
  public partial class ORCALibGetClaimPatientInfo : global::ProtoBuf.IExtensible
  {
    public ORCALibGetClaimPatientInfo() {}
    
    private string _upd_date = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"upd_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string upd_date
    {
      get { return _upd_date; }
      set { _upd_date = value; }
    }
    private string _upd_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"upd_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string upd_id
    {
      get { return _upd_id; }
      set { _upd_id = value; }
    }
    private string _hosp_code = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hosp_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hosp_code
    {
      get { return _hosp_code; }
      set { _hosp_code = value; }
    }
    private string _pkoif1101 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pkoif1101", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pkoif1101
    {
      get { return _pkoif1101; }
      set { _pkoif1101 = value; }
    }
    private string _doc_uid = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"doc_uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doc_uid
    {
      get { return _doc_uid; }
      set { _doc_uid = value; }
    }
    private string _cm_id = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cm_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cm_id
    {
      get { return _cm_id; }
      set { _cm_id = value; }
    }
    private string _license = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"license", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string license
    {
      get { return _license; }
      set { _license = value; }
    }
    private string _bunho = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _suname1 = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"suname1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suname1
    {
      get { return _suname1; }
      set { _suname1 = value; }
    }
    private string _suname2 = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"suname2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suname2
    {
      get { return _suname2; }
      set { _suname2 = value; }
    }
    private string _suname3 = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"suname3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suname3
    {
      get { return _suname3; }
      set { _suname3 = value; }
    }
    private string _degree = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"degree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string degree
    {
      get { return _degree; }
      set { _degree = value; }
    }
    private string _sex = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _birth = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"birth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string birth
    {
      get { return _birth; }
      set { _birth = value; }
    }
    private string _nationality = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"nationality", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nationality
    {
      get { return _nationality; }
      set { _nationality = value; }
    }
    private string _marital = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"marital", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string marital
    {
      get { return _marital; }
      set { _marital = value; }
    }
    private string _accnt_num = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"accnt_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accnt_num
    {
      get { return _accnt_num; }
      set { _accnt_num = value; }
    }
    private string _socialid = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"socialid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string socialid
    {
      get { return _socialid; }
      set { _socialid = value; }
    }
    private string _email = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private string _death = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"death", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string death
    {
      get { return _death; }
      set { _death = value; }
    }
    private string _death_date = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"death_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string death_date
    {
      get { return _death_date; }
      set { _death_date = value; }
    }
    private string _end_flag = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"end_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string end_flag
    {
      get { return _end_flag; }
      set { _end_flag = value; }
    }
    private string _pkoif1102 = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"pkoif1102", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pkoif1102
    {
      get { return _pkoif1102; }
      set { _pkoif1102 = value; }
    }
    private string _addr_code = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"addr_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string addr_code
    {
      get { return _addr_code; }
      set { _addr_code = value; }
    }
    private string _addr_full = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"addr_full", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string addr_full
    {
      get { return _addr_full; }
      set { _addr_full = value; }
    }
    private string _prefecture = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"prefecture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefecture
    {
      get { return _prefecture; }
      set { _prefecture = value; }
    }
    private string _city_b = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"city_b", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string city_b
    {
      get { return _city_b; }
      set { _city_b = value; }
    }
    private string _town = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"town", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string town
    {
      get { return _town; }
      set { _town = value; }
    }
    private string _home_num = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"home_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string home_num
    {
      get { return _home_num; }
      set { _home_num = value; }
    }
    private string _zip = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"zip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zip
    {
      get { return _zip; }
      set { _zip = value; }
    }
    private string _country_b = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"country_b", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string country_b
    {
      get { return _country_b; }
      set { _country_b = value; }
    }
    private string _pkoif1103 = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"pkoif1103", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pkoif1103
    {
      get { return _pkoif1103; }
      set { _pkoif1103 = value; }
    }
    private string _tel_code = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"tel_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tel_code
    {
      get { return _tel_code; }
      set { _tel_code = value; }
    }
    private string _area = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"area", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string area
    {
      get { return _area; }
      set { _area = value; }
    }
    private string _city_c = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"city_c", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string city_c
    {
      get { return _city_c; }
      set { _city_c = value; }
    }
    private string _num = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num
    {
      get { return _num; }
      set { _num = value; }
    }
    private string _extension = "";
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extension
    {
      get { return _extension; }
      set { _extension = value; }
    }
    private string _country_c = "";
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"country_c", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string country_c
    {
      get { return _country_c; }
      set { _country_c = value; }
    }
    private string _memo = "";
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"memo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string memo
    {
      get { return _memo; }
      set { _memo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
