//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"INV4001U00ExportCSVInfo")]
  public partial class INV4001U00ExportCSVInfo : global::ProtoBuf.IExtensible
  {
    public INV4001U00ExportCSVInfo() {}
    
    private string _row_num = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"row_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string row_num
    {
      get { return _row_num; }
      set { _row_num = value; }
    }
    private string _churi_date = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"churi_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string churi_date
    {
      get { return _churi_date; }
      set { _churi_date = value; }
    }
    private string _import_time = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"import_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string import_time
    {
      get { return _import_time; }
      set { _import_time = value; }
    }
    private string _jaeryo_code = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"jaeryo_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_code
    {
      get { return _jaeryo_code; }
      set { _jaeryo_code = value; }
    }
    private string _jaeryo_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"jaeryo_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_name
    {
      get { return _jaeryo_name; }
      set { _jaeryo_name = value; }
    }
    private string _start_date = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"start_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string start_date
    {
      get { return _start_date; }
      set { _start_date = value; }
    }
    private string _lot = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"lot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lot
    {
      get { return _lot; }
      set { _lot = value; }
    }
    private string _expired_date = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"expired_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string expired_date
    {
      get { return _expired_date; }
      set { _expired_date = value; }
    }
    private string _ipgo_qty = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ipgo_qty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipgo_qty
    {
      get { return _ipgo_qty; }
      set { _ipgo_qty = value; }
    }
    private string _ipgo_danui_name = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"ipgo_danui_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipgo_danui_name
    {
      get { return _ipgo_danui_name; }
      set { _ipgo_danui_name = value; }
    }
    private string _ipgo_type = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"ipgo_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipgo_type
    {
      get { return _ipgo_type; }
      set { _ipgo_type = value; }
    }
    private string _upd_id = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"upd_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string upd_id
    {
      get { return _upd_id; }
      set { _upd_id = value; }
    }
    private string _ipgo_danga = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"ipgo_danga", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipgo_danga
    {
      get { return _ipgo_danga; }
      set { _ipgo_danga = value; }
    }
    private string _qty_ipgo_danga = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"qty_ipgo_danga", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string qty_ipgo_danga
    {
      get { return _qty_ipgo_danga; }
      set { _qty_ipgo_danga = value; }
    }
    private string _import_code = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"import_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string import_code
    {
      get { return _import_code; }
      set { _import_code = value; }
    }
    private string _comment = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string comment
    {
      get { return _comment; }
      set { _comment = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
