//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NUR2001U04CheckExistMedicalRecordInfo")]
  public partial class NUR2001U04CheckExistMedicalRecordInfo : global::ProtoBuf.IExtensible
  {
    public NUR2001U04CheckExistMedicalRecordInfo() {}
    
    private string _emr_record_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"emr_record_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string emr_record_id
    {
      get { return _emr_record_id; }
      set { _emr_record_id = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _metadata = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string metadata
    {
      get { return _metadata; }
      set { _metadata = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _record_log = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"record_log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string record_log
    {
      get { return _record_log; }
      set { _record_log = value; }
    }
    private string _lock_flg = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lock_flg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lock_flg
    {
      get { return _lock_flg; }
      set { _lock_flg = value; }
    }
    private string _hosp_code = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hosp_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hosp_code
    {
      get { return _hosp_code; }
      set { _hosp_code = value; }
    }
    private string _bunho = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _sys_id = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sys_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sys_id
    {
      get { return _sys_id; }
      set { _sys_id = value; }
    }
    private string _upd_id = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"upd_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string upd_id
    {
      get { return _upd_id; }
      set { _upd_id = value; }
    }
    private string _created = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"created", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string created
    {
      get { return _created; }
      set { _created = value; }
    }
    private string _updated = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"updated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string updated
    {
      get { return _updated; }
      set { _updated = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
