//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS2015U40EmrHistoryMedicalRecordInfo")]
  public partial class OCS2015U40EmrHistoryMedicalRecordInfo : global::ProtoBuf.IExtensible
  {
    public OCS2015U40EmrHistoryMedicalRecordInfo() {}
    
    private string _sys_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sys_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sys_id
    {
      get { return _sys_id; }
      set { _sys_id = value; }
    }
    private string _created = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"created", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string created
    {
      get { return _created; }
      set { _created = value; }
    }
    private string _memo = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"memo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string memo
    {
      get { return _memo; }
      set { _memo = value; }
    }
    private string _active_flg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"active_flg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string active_flg
    {
      get { return _active_flg; }
      set { _active_flg = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _author = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"author", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string author
    {
      get { return _author; }
      set { _author = value; }
    }
    private string _emr_record_id = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"emr_record_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string emr_record_id
    {
      get { return _emr_record_id; }
      set { _emr_record_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
