//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: phys_service.proto
// Note: requires additional types generated from: phys_model.proto
// Note: requires additional types generated from: system_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PHY8002U00GrdPHYRequest")]
  public partial class PHY8002U00GrdPHYRequest : global::ProtoBuf.IExtensible
  {
    public PHY8002U00GrdPHYRequest() {}
    
    private string _fk_ocs = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fk_ocs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fk_ocs
    {
      get { return _fk_ocs; }
      set { _fk_ocs = value; }
    }
    private string _kanja_no = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"kanja_no", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string kanja_no
    {
      get { return _kanja_no; }
      set { _kanja_no = value; }
    }
    private string _fk_ocs_irai = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fk_ocs_irai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fk_ocs_irai
    {
      get { return _fk_ocs_irai; }
      set { _fk_ocs_irai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
