//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHIS.CloudConnector.Messaging
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"NuroPatientInsuranceListItemInfo")]
    public partial class NuroPatientInsuranceListItemInfo : global::ProtoBuf.IExtensible
    {
        public NuroPatientInsuranceListItemInfo() { }

        private string _status = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string status
        {
            get { return _status; }
            set { _status = value; }
        }
        private string _insur_code = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"insur_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string insur_code
        {
            get { return _insur_code; }
            set { _insur_code = value; }
        }
        private string _insur_name = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"insur_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string insur_name
        {
            get { return _insur_name; }
            set { _insur_name = value; }
        }
        private string _last_check_date = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"last_check_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string last_check_date
        {
            get { return _last_check_date; }
            set { _last_check_date = value; }
        }
        private string _start_date = "";
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"start_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string start_date
        {
            get { return _start_date; }
            set { _start_date = value; }
        }
        private string _patient_code = "";
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"patient_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string patient_code
        {
            get { return _patient_code; }
            set { _patient_code = value; }
        }
        private string _budamja_patient_code = "";
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"budamja_patient_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string budamja_patient_code
        {
            get { return _budamja_patient_code; }
            set { _budamja_patient_code = value; }
        }
        private string _insur_jiyeok = "";
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"insur_jiyeok", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string insur_jiyeok
        {
            get { return _insur_jiyeok; }
            set { _insur_jiyeok = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}