//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuro_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NuroNUR1001R00GetTempListItemInfo")]
  public partial class NuroNUR1001R00GetTempListItemInfo : global::ProtoBuf.IExtensible
  {
    public NuroNUR1001R00GetTempListItemInfo() {}
    
    private string _doctor_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"doctor_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_name
    {
      get { return _doctor_name; }
      set { _doctor_name = value; }
    }
    private string _num1 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num1
    {
      get { return _num1; }
      set { _num1 = value; }
    }
    private string _num2 = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num2
    {
      get { return _num2; }
      set { _num2 = value; }
    }
    private string _num3 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num3
    {
      get { return _num3; }
      set { _num3 = value; }
    }
    private string _num4 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"num4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num4
    {
      get { return _num4; }
      set { _num4 = value; }
    }
    private string _num5 = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"num5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num5
    {
      get { return _num5; }
      set { _num5 = value; }
    }
    private string _num6 = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"num6", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num6
    {
      get { return _num6; }
      set { _num6 = value; }
    }
    private string _num7 = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"num7", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num7
    {
      get { return _num7; }
      set { _num7 = value; }
    }
    private string _num8 = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"num8", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num8
    {
      get { return _num8; }
      set { _num8 = value; }
    }
    private string _num9 = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"num9", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num9
    {
      get { return _num9; }
      set { _num9 = value; }
    }
    private string _num10 = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"num10", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num10
    {
      get { return _num10; }
      set { _num10 = value; }
    }
    private string _num11 = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"num11", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num11
    {
      get { return _num11; }
      set { _num11 = value; }
    }
    private string _num12 = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"num12", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num12
    {
      get { return _num12; }
      set { _num12 = value; }
    }
    private string _num13 = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"num13", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num13
    {
      get { return _num13; }
      set { _num13 = value; }
    }
    private string _num14 = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"num14", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num14
    {
      get { return _num14; }
      set { _num14 = value; }
    }
    private string _num15 = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"num15", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num15
    {
      get { return _num15; }
      set { _num15 = value; }
    }
    private string _num16 = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"num16", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num16
    {
      get { return _num16; }
      set { _num16 = value; }
    }
    private string _num17 = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"num17", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num17
    {
      get { return _num17; }
      set { _num17 = value; }
    }
    private string _num18 = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"num18", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num18
    {
      get { return _num18; }
      set { _num18 = value; }
    }
    private string _num19 = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"num19", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num19
    {
      get { return _num19; }
      set { _num19 = value; }
    }
    private string _num20 = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"num20", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num20
    {
      get { return _num20; }
      set { _num20 = value; }
    }
    private string _num21 = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"num21", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num21
    {
      get { return _num21; }
      set { _num21 = value; }
    }
    private string _num22 = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"num22", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num22
    {
      get { return _num22; }
      set { _num22 = value; }
    }
    private string _num23 = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"num23", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num23
    {
      get { return _num23; }
      set { _num23 = value; }
    }
    private string _num24 = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"num24", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num24
    {
      get { return _num24; }
      set { _num24 = value; }
    }
    private string _num25 = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"num25", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num25
    {
      get { return _num25; }
      set { _num25 = value; }
    }
    private string _num26 = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"num26", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num26
    {
      get { return _num26; }
      set { _num26 = value; }
    }
    private string _num27 = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"num27", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num27
    {
      get { return _num27; }
      set { _num27 = value; }
    }
    private string _num28 = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"num28", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num28
    {
      get { return _num28; }
      set { _num28 = value; }
    }
    private string _num29 = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"num29", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num29
    {
      get { return _num29; }
      set { _num29 = value; }
    }
    private string _num30 = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"num30", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num30
    {
      get { return _num30; }
      set { _num30 = value; }
    }
    private string _num31 = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"num31", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string num31
    {
      get { return _num31; }
      set { _num31 = value; }
    }
    private string _last_day = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"last_day", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string last_day
    {
      get { return _last_day; }
      set { _last_day = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
