//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ORDERTRANSGrdWoichulInfo")]
  public partial class ORDERTRANSGrdWoichulInfo : global::ProtoBuf.IExtensible
  {
    public ORDERTRANSGrdWoichulInfo() {}
    
    private string _fkinp1001 = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fkinp1001", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fkinp1001
    {
      get { return _fkinp1001; }
      set { _fkinp1001 = value; }
    }
    private string _fk_out_date = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fk_out_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fk_out_date
    {
      get { return _fk_out_date; }
      set { _fk_out_date = value; }
    }
    private string _bunho = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _out_date = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"out_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string out_date
    {
      get { return _out_date; }
      set { _out_date = value; }
    }
    private string _out_time = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"out_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string out_time
    {
      get { return _out_time; }
      set { _out_time = value; }
    }
    private string _in_hope_date = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"in_hope_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string in_hope_date
    {
      get { return _in_hope_date; }
      set { _in_hope_date = value; }
    }
    private string _in_hope_time = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"in_hope_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string in_hope_time
    {
      get { return _in_hope_time; }
      set { _in_hope_time = value; }
    }
    private string _in_true_date = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"in_true_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string in_true_date
    {
      get { return _in_true_date; }
      set { _in_true_date = value; }
    }
    private string _in_true_time = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"in_true_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string in_true_time
    {
      get { return _in_true_time; }
      set { _in_true_time = value; }
    }
    private string _out_object_text = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"out_object_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string out_object_text
    {
      get { return _out_object_text; }
      set { _out_object_text = value; }
    }
    private string _start_date = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"start_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string start_date
    {
      get { return _start_date; }
      set { _start_date = value; }
    }
    private string _end_date = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"end_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string end_date
    {
      get { return _end_date; }
      set { _end_date = value; }
    }
    private string _acting_yn = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"acting_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string acting_yn
    {
      get { return _acting_yn; }
      set { _acting_yn = value; }
    }
    private string _select_yn = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"select_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string select_yn
    {
      get { return _select_yn; }
      set { _select_yn = value; }
    }
    private string _send_yn = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"send_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string send_yn
    {
      get { return _send_yn; }
      set { _send_yn = value; }
    }
    private string _seq = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
