//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PHY2001U04GrdPatientListInfo")]
  public partial class PHY2001U04GrdPatientListInfo : global::ProtoBuf.IExtensible
  {
    public PHY2001U04GrdPatientListInfo() {}
    
    private string _gwa = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gwa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gwa
    {
      get { return _gwa; }
      set { _gwa = value; }
    }
    private string _gwa_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gwa_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gwa_name
    {
      get { return _gwa_name; }
      set { _gwa_name = value; }
    }
    private string _bunho = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _suname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"suname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suname
    {
      get { return _suname; }
      set { _suname = value; }
    }
    private string _suname2 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"suname2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suname2
    {
      get { return _suname2; }
      set { _suname2 = value; }
    }
    private string _naewon_date = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"naewon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string naewon_date
    {
      get { return _naewon_date; }
      set { _naewon_date = value; }
    }
    private string _doctor = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"doctor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor
    {
      get { return _doctor; }
      set { _doctor = value; }
    }
    private string _doctor_name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"doctor_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_name
    {
      get { return _doctor_name; }
      set { _doctor_name = value; }
    }
    private string _naewon_type = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"naewon_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string naewon_type
    {
      get { return _naewon_type; }
      set { _naewon_type = value; }
    }
    private string _jubsu_no = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"jubsu_no", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jubsu_no
    {
      get { return _jubsu_no; }
      set { _jubsu_no = value; }
    }
    private string _birth = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"birth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string birth
    {
      get { return _birth; }
      set { _birth = value; }
    }
    private string _age_sex = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"age_sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string age_sex
    {
      get { return _age_sex; }
      set { _age_sex = value; }
    }
    private string _out_res_key = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"out_res_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string out_res_key
    {
      get { return _out_res_key; }
      set { _out_res_key = value; }
    }
    private string _jubsu_time = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"jubsu_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jubsu_time
    {
      get { return _jubsu_time; }
      set { _jubsu_time = value; }
    }
    private string _order_end_yn = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"order_end_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_end_yn
    {
      get { return _order_end_yn; }
      set { _order_end_yn = value; }
    }
    private string _hold_yn = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"hold_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hold_yn
    {
      get { return _hold_yn; }
      set { _hold_yn = value; }
    }
    private string _result_yn = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"result_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string result_yn
    {
      get { return _result_yn; }
      set { _result_yn = value; }
    }
    private string _reser_yn = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"reser_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reser_yn
    {
      get { return _reser_yn; }
      set { _reser_yn = value; }
    }
    private string _ipwon_yn = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"ipwon_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipwon_yn
    {
      get { return _ipwon_yn; }
      set { _ipwon_yn = value; }
    }
    private string _sunab_yn = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"sunab_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sunab_yn
    {
      get { return _sunab_yn; }
      set { _sunab_yn = value; }
    }
    private string _naewon_yn = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"naewon_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string naewon_yn
    {
      get { return _naewon_yn; }
      set { _naewon_yn = value; }
    }
    private string _jubsu_gubun = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"jubsu_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jubsu_gubun
    {
      get { return _jubsu_gubun; }
      set { _jubsu_gubun = value; }
    }
    private string _jubsu_gubun_name = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"jubsu_gubun_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jubsu_gubun_name
    {
      get { return _jubsu_gubun_name; }
      set { _jubsu_gubun_name = value; }
    }
    private string _remark = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string remark
    {
      get { return _remark; }
      set { _remark = value; }
    }
    private string _arrive_time = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"arrive_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string arrive_time
    {
      get { return _arrive_time; }
      set { _arrive_time = value; }
    }
    private string _gubun = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gubun
    {
      get { return _gubun; }
      set { _gubun = value; }
    }
    private string _last_naewon_date = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"last_naewon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string last_naewon_date
    {
      get { return _last_naewon_date; }
      set { _last_naewon_date = value; }
    }
    private string _ocs_comment = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"ocs_comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ocs_comment
    {
      get { return _ocs_comment; }
      set { _ocs_comment = value; }
    }
    private string _chojae = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"chojae", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chojae
    {
      get { return _chojae; }
      set { _chojae = value; }
    }
    private string _group_key = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"group_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string group_key
    {
      get { return _group_key; }
      set { _group_key = value; }
    }
    private string _bunho_type = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"bunho_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho_type
    {
      get { return _bunho_type; }
      set { _bunho_type = value; }
    }
    private string _kaigo_yn = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"kaigo_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string kaigo_yn
    {
      get { return _kaigo_yn; }
      set { _kaigo_yn = value; }
    }
    private string _gaein = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"gaein", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gaein
    {
      get { return _gaein; }
      set { _gaein = value; }
    }
    private string _bp_to = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"bp_to", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bp_to
    {
      get { return _bp_to; }
      set { _bp_to = value; }
    }
    private string _bp_from = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"bp_from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bp_from
    {
      get { return _bp_from; }
      set { _bp_from = value; }
    }
    private string _pulse = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"pulse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pulse
    {
      get { return _pulse; }
      set { _pulse = value; }
    }
    private string _body_heat = "";
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"body_heat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string body_heat
    {
      get { return _body_heat; }
      set { _body_heat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
