//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: bass_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BAS0110Q00GrdBAS0110ItemInfo")]
  public partial class BAS0110Q00GrdBAS0110ItemInfo : global::ProtoBuf.IExtensible
  {
    public BAS0110Q00GrdBAS0110ItemInfo() {}
    
    private string _johap = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"johap", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string johap
    {
      get { return _johap; }
      set { _johap = value; }
    }
    private string _start_date = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"start_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string start_date
    {
      get { return _start_date; }
      set { _start_date = value; }
    }
    private string _johap_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"johap_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string johap_name
    {
      get { return _johap_name; }
      set { _johap_name = value; }
    }
    private string _johap_gubun = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"johap_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string johap_gubun
    {
      get { return _johap_gubun; }
      set { _johap_gubun = value; }
    }
    private string _zip_code1 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"zip_code1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zip_code1
    {
      get { return _zip_code1; }
      set { _zip_code1 = value; }
    }
    private string _zip_code2 = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"zip_code2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zip_code2
    {
      get { return _zip_code2; }
      set { _zip_code2 = value; }
    }
    private string _address = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }
    private string _tel = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"tel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tel
    {
      get { return _tel; }
      set { _tel = value; }
    }
    private string _law_no = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"law_no", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string law_no
    {
      get { return _law_no; }
      set { _law_no = value; }
    }
    private string _dodobuhyeun_no = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dodobuhyeun_no", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dodobuhyeun_no
    {
      get { return _dodobuhyeun_no; }
      set { _dodobuhyeun_no = value; }
    }
    private string _boheomja_no = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"boheomja_no", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string boheomja_no
    {
      get { return _boheomja_no; }
      set { _boheomja_no = value; }
    }
    private string _cd = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"cd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cd
    {
      get { return _cd; }
      set { _cd = value; }
    }
    private string _giho = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"giho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string giho
    {
      get { return _giho; }
      set { _giho = value; }
    }
    private string _remark = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string remark
    {
      get { return _remark; }
      set { _remark = value; }
    }
    private string _check_digit_yn = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"check_digit_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string check_digit_yn
    {
      get { return _check_digit_yn; }
      set { _check_digit_yn = value; }
    }
    private string _johap_gubun_name = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"johap_gubun_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string johap_gubun_name
    {
      get { return _johap_gubun_name; }
      set { _johap_gubun_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
