SET DEFINE OFF;
Insert into MEDI.ADM4300
   (USER_ID, SYS_ID, SEQ, MENU_TP, MENU_LEVEL, 
    PGM_NM, TR_ID, PGM_GRP_ID, PGM_SYS_ID, PGM_ID, 
    PGM_ENT_GRAD, PGM_UPD_GRAD, PGM_DUP_YN, PGM_ACS_YN, PGM_OPEN_TP, 
    ASM_NAME, ASM_PATH, ASM_VER, HOSP_CODE)
 Values
   ('99999', 'OCSO', 100, 'P', 2, 
    'OCS2015U00', '00106', 'OCS', 'OCSO', 'OCS2015U00', 
    0, 0, 'N', 'Y', 'PPS', 
    'OCSO.OCS2015U00.dll', 'OCS/OCSO/BSA', '1.0.0.0', 'K01');
COMMIT;
