//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrgsDRG5100P01ProcAtcInterfaceRequest")]
  public partial class DrgsDRG5100P01ProcAtcInterfaceRequest : global::ProtoBuf.IExtensible
  {
    public DrgsDRG5100P01ProcAtcInterfaceRequest() {}
    
    private string _jubsu_date = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"jubsu_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jubsu_date
    {
      get { return _jubsu_date; }
      set { _jubsu_date = value; }
    }
    private string _drg_bunho = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"drg_bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string drg_bunho
    {
      get { return _drg_bunho; }
      set { _drg_bunho = value; }
    }
    private string _data_dubun = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data_dubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data_dubun
    {
      get { return _data_dubun; }
      set { _data_dubun = value; }
    }
    private string _io_gubun = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"io_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_gubun
    {
      get { return _io_gubun; }
      set { _io_gubun = value; }
    }
    private string _bunho = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _fkout1001 = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fkout1001", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fkout1001
    {
      get { return _fkout1001; }
      set { _fkout1001 = value; }
    }
    private string _send_yn = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"send_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string send_yn
    {
      get { return _send_yn; }
      set { _send_yn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
