//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service2.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS2015U03OrderGubunRequest")]
  public partial class OCS2015U03OrderGubunRequest : global::ProtoBuf.IExtensible
  {
    public OCS2015U03OrderGubunRequest() {}
    
    private string _f_hopital_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"f_hopital_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string f_hopital_code
    {
      get { return _f_hopital_code; }
      set { _f_hopital_code = value; }
    }
    private string _f_patient_code = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"f_patient_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string f_patient_code
    {
      get { return _f_patient_code; }
      set { _f_patient_code = value; }
    }
    private string _f_reservation_code = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"f_reservation_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string f_reservation_code
    {
      get { return _f_reservation_code; }
      set { _f_reservation_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
