//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
// Note: requires additional types generated from: mixed_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Bas0260U00LayDupCheckResponse")]
  public partial class Bas0260U00LayDupCheckResponse : global::ProtoBuf.IExtensible
  {
    public Bas0260U00LayDupCheckResponse() {}
    
    private string _lay_dup_result = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"lay_dup_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lay_dup_result
    {
      get { return _lay_dup_result; }
      set { _lay_dup_result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
