//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BAS0210U00grdBAS0210Response")]
  public partial class BAS0210U00grdBAS0210Response : global::ProtoBuf.IExtensible
  {
    public BAS0210U00grdBAS0210Response() {}
    
    private readonly global::System.Collections.Generic.List<BAS0210U00grdBAS0210ItemInfo> _grd_bas0210 = new global::System.Collections.Generic.List<BAS0210U00grdBAS0210ItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grd_bas0210", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BAS0210U00grdBAS0210ItemInfo> grd_bas0210
    {
      get { return _grd_bas0210; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
