//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BAS0210U00grdBAS0210GridColumnChangedResponse")]
  public partial class BAS0210U00grdBAS0210GridColumnChangedResponse : global::ProtoBuf.IExtensible
  {
    public BAS0210U00grdBAS0210GridColumnChangedResponse() {}
    
    private readonly global::System.Collections.Generic.List<BAS0210U00grdBAS0210GridColumnChangedItemInfo> _grid_column_changed = new global::System.Collections.Generic.List<BAS0210U00grdBAS0210GridColumnChangedItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grid_column_changed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BAS0210U00grdBAS0210GridColumnChangedItemInfo> grid_column_changed
    {
      get { return _grid_column_changed; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
