//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Sample.proto
// Note: requires additional types generated from: mixed_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BAS0212U00TransactionalRequest")]
  public partial class BAS0212U00TransactionalRequest : global::ProtoBuf.IExtensible
  {
    public BAS0212U00TransactionalRequest() {}
    
    private readonly global::System.Collections.Generic.List<BAS0212U00GrdItemInfo> _grd_init = new global::System.Collections.Generic.List<BAS0212U00GrdItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grd_init", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BAS0212U00GrdItemInfo> grd_init
    {
      get { return _grd_init; }
    }
  
    private string _user_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
