//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input(1).proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadCbxLanguageRequest")]
  public partial class LoadCbxLanguageRequest : global::ProtoBuf.IExtensible
  {
    public LoadCbxLanguageRequest() {}
    
    private string _property_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"property_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string property_code
    {
      get { return _property_code; }
      set { _property_code = value; }
    }
    private string _active_flg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"active_flg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string active_flg
    {
      get { return _active_flg; }
      set { _active_flg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
