//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCH0109U00XSavePerformerRequest")]
  public partial class SCH0109U00XSavePerformerRequest : global::ProtoBuf.IExtensible
  {
    public SCH0109U00XSavePerformerRequest() {}
    
    private readonly global::System.Collections.Generic.List<SCH0109U00GrdDetailInfo> _grd_detail_list = new global::System.Collections.Generic.List<SCH0109U00GrdDetailInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grd_detail_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SCH0109U00GrdDetailInfo> grd_detail_list
    {
      get { return _grd_detail_list; }
    }
  
    private string _user_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
