//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SchsSCH0201U99DateScheduleListResponse")]
  public partial class SchsSCH0201U99DateScheduleListResponse : global::ProtoBuf.IExtensible
  {
    public SchsSCH0201U99DateScheduleListResponse() {}
    
    private readonly global::System.Collections.Generic.List<SchsSCH0201U99DateScheduleItemInfo> _date_schedule_item = new global::System.Collections.Generic.List<SchsSCH0201U99DateScheduleItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"date_schedule_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SchsSCH0201U99DateScheduleItemInfo> date_schedule_item
    {
      get { return _date_schedule_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
