//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCS2016U00UpdateReplyRequest")]
  public partial class OCS2016U00UpdateReplyRequest : global::ProtoBuf.IExtensible
  {
    public OCS2016U00UpdateReplyRequest() {}
    
    private readonly global::System.Collections.Generic.List<OCS2016U00LoadDiscussionInfo> _discussion_list = new global::System.Collections.Generic.List<OCS2016U00LoadDiscussionInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"discussion_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OCS2016U00LoadDiscussionInfo> discussion_list
    {
      get { return _discussion_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
