//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input(1).proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCSACT2CompositeRequest")]
  public partial class OCSACT2CompositeRequest : global::ProtoBuf.IExtensible
  {
    public OCSACT2CompositeRequest() {}
    
    private OCSACTCboTimeAndSystemRequest _cbo_time_and_sys = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cbo_time_and_sys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OCSACTCboTimeAndSystemRequest cbo_time_and_sys
    {
      get { return _cbo_time_and_sys; }
      set { _cbo_time_and_sys = value; }
    }
    private OCSACT2GetComboUserRequest _cbo_user = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cbo_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OCSACT2GetComboUserRequest cbo_user
    {
      get { return _cbo_user; }
      set { _cbo_user = value; }
    }
    private OCSACT2GetGrdPaListRequest _grd_pa_list = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"grd_pa_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OCSACT2GetGrdPaListRequest grd_pa_list
    {
      get { return _grd_pa_list; }
      set { _grd_pa_list = value; }
    }
    private OCSACTCboSystemSelectedIndexChangedRequest _cbo_selected_index_change = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cbo_selected_index_change", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OCSACTCboSystemSelectedIndexChangedRequest cbo_selected_index_change
    {
      get { return _cbo_selected_index_change; }
      set { _cbo_selected_index_change = value; }
    }
    private OCSACTLayconstantConstRequest _lay_constant_cons = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lay_constant_cons", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OCSACTLayconstantConstRequest lay_constant_cons
    {
      get { return _lay_constant_cons; }
      set { _lay_constant_cons = value; }
    }
    private OCSACTLayconstantAlarmRequest _lay_constant_alarm = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lay_constant_alarm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OCSACTLayconstantAlarmRequest lay_constant_alarm
    {
      get { return _lay_constant_alarm; }
      set { _lay_constant_alarm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
