//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input(1).proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCSACT2CompositeSecondResponse")]
  public partial class OCSACT2CompositeSecondResponse : global::ProtoBuf.IExtensible
  {
    public OCSACT2CompositeSecondResponse() {}
    
    private OCS2015U00GetPatientInfoResponse _get_patient_info_res = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"get_patient_info_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OCS2015U00GetPatientInfoResponse get_patient_info_res
    {
      get { return _get_patient_info_res; }
      set { _get_patient_info_res = value; }
    }
    private NUR1016U00GrdNUR1016Response _grd_nur1016_res = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"grd_nur1016_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NUR1016U00GrdNUR1016Response grd_nur1016_res
    {
      get { return _grd_nur1016_res; }
      set { _grd_nur1016_res = value; }
    }
    private NUR1017U00GrdNUR1017Response _grd_nur1017_res = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"grd_nur1017_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NUR1017U00GrdNUR1017Response grd_nur1017_res
    {
      get { return _grd_nur1017_res; }
      set { _grd_nur1017_res = value; }
    }
    private OUT0106U00GridListResponse _grd_list_out0106u00_res = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"grd_list_out0106u00_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OUT0106U00GridListResponse grd_list_out0106u00_res
    {
      get { return _grd_list_out0106u00_res; }
      set { _grd_list_out0106u00_res = value; }
    }
    private GetPatientByCodeResponse _get_patient_bycode_res = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"get_patient_bycode_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GetPatientByCodeResponse get_patient_bycode_res
    {
      get { return _get_patient_bycode_res; }
      set { _get_patient_bycode_res = value; }
    }
    private OcsLoadInputAndVisibleControlResponse _input_visible_res = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"input_visible_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OcsLoadInputAndVisibleControlResponse input_visible_res
    {
      get { return _input_visible_res; }
      set { _input_visible_res = value; }
    }
    private OcsLoadInputTabResponse _input_tab_res = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"input_tab_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OcsLoadInputTabResponse input_tab_res
    {
      get { return _input_tab_res; }
      set { _input_tab_res = value; }
    }
    private InjsINJ1001U01DetailListResponse _detail_list_res = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"detail_list_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public InjsINJ1001U01DetailListResponse detail_list_res
    {
      get { return _detail_list_res; }
      set { _detail_list_res = value; }
    }
    private CPL2010U00CheckInjCplOrderResponse _check_inj_res = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"check_inj_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CPL2010U00CheckInjCplOrderResponse check_inj_res
    {
      get { return _check_inj_res; }
      set { _check_inj_res = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
