//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CPL3020U00FwkResultGetYRequest")]
  public partial class CPL3020U00FwkResultGetYRequest : global::ProtoBuf.IExtensible
  {
    public CPL3020U00FwkResultGetYRequest() {}
    
    private string _result_form = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result_form", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string result_form
    {
      get { return _result_form; }
      set { _result_form = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
